### ISSUE TITLE
Create custom submission forms for NDLTD collection /18725

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#101]
DSpace documentation: https://wiki.duraspace.org/display/DSDOC5x/Submission+User+Interface 

Nice presentation on customizing the DSpace submission process here: http://www.slideshare.net/bramluyten/secrets-of-the-dspace-submission-form 

Here are the required fields for the submission user interface for this collection: 

dc.contributor.author
dc.contributor.committeechair
dc.contributor.committeecochair
dc.contributor.committeemember
dc.contributor.department
dc.date.accessioned
dc.date.available
dc.date.issued
dc.date.submitted
dc.description.abstract
dc.description.admin
dc.description.degree
dc.description.provenance
dc.format.medium
dc.format.mimetype
dc.format.extent
dc..identifier.oclc
dc.identifier.other
dc.identifier.sourceurl
dc.language.iso
dc.publisher
dc.relation.haspart
dc.rights
dc.subject
dc.subject.lcc
dc.subject.lcsh
dc.subject.mesh
dc.title
dc.type
dc.type.dmitype
thesis.degree.level
thesis.degree.name
thesis.degree.grantor
thesis.degree.discipline

**Comment by alawvt** [comment]
The form for this collection probably will not need:
dc.date.accessioned - system generated info
dc.date.available - system generated info
dc.description.admin
dc.description.provenance- system generated info, have used for email addresses
dc..identifier.oclc - unlikely
dc.publisher - usually dissertations are unpublished
dc.relation.haspart
dc.subject.lcc - unlikely
dc.subject.lcsh - unlikely
dc.subject.mesh - unlikely
dc.title
dc.type
dc.type.dmitype

thesis.degree.discipline=dc.contributor.department, so that could be added automatically

thesis.degree.level could be a drop down - doctoral or masters (or other?)

**Comment by alawvt** [comment]
I'd suggest doing the OMALS one before this one.

**Comment by alawvt** [comment]
Reference: NDLTD ETD-MS v. 1.1 metadata schema, http://www.ndltd.org/standards/metadata.
