### ISSUE TITLE
Review default submission forms

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#105]

**Comment by amandafrench** [comment]
Current default item submission (first two screens): 

![screenshot 2016-01-06 15 57 48](https://cloud.githubusercontent.com/assets/227453/12154565/41a9be2c-b48e-11e5-921f-f9a359d32f1c.png)
![screenshot 2016-01-06 15 58 25](https://cloud.githubusercontent.com/assets/227453/12154577/5897b896-b48e-11e5-88c6-9af128c3b32b.png)
![screenshot 2016-01-06 15 59 24](https://cloud.githubusercontent.com/assets/227453/12154605/7b5b67ce-b48e-11e5-8542-b61f74a0e43f.png)

**Comment by alawvt** [comment]
@amandafrench, will all these fields remain on the default submission form? Will they all be on one page? Knowing this would help me set up the moving image fields for @AmberPoo1.

**Comment by amandafrench** [comment]
As per this morning's standup, we'll review the default submission forms together in a separate meeting. I do want to remove some (Subject Categories and Other Description at the very least) and combine them onto one page: I think we're agreed on that.

**Comment by alawvt** [comment]
**New default submission form**

**dc.type**
Label: Item Type
Hint: Select the type(s) of content you are depositing. To select more than one value in the list, you may have to hold down the "CTRL" or "Shift" key. Examples: Article, Learning Object, Video Recording and Presentation. 

Modify common_types value-pairs list (remove others)
- Audio recording
- Article 
- Book
- Book chapter
- Dataset
- Dissertation
- Image
- Learning Object
- Map
- Presentation
- Software
- Report
- Thesis
- Video recording
- Other

**dc.contributor.author**
Label: Author(s)/Creator(s)
Hint: Enter the name(s) of the author(s) or creator(s). Enter each name individually, then click "Add."
To use VTechWorks' name lookup function, click "Lookup" and you will be directed to an index of VTechWorks' creator and contributor names. Examples: Leavis, Q. D.; Einstein, Albert; Lovelace, Ada

associated: change messages.xml for name input-type #188

**dc.title**
Label: Title
Hint: Enter the title or name of the item. If a title is not provided, create one that appropriately describes the item. Examples: Extended Boolean Information Retrieval, Ossian and the Genres of Culture, Chemistry of Arsenic Removal During Coagulation and Fe-Mn Oxidation

**dc.title.serial** (new field)
Label: Journal Title
Hint: Examples: _Foreign Affairs, PLOS One, Nature_
[TODO: Need to develop language for Sherpa Romeo lookup]

**dc.date.issued**
Label: Date
Hint: Enter date of publication or public distribution. A year is required, but month and day are optional. If the item has not been previously published, enter today's date. Examples: 2010, 1969 July 01, 1995 August

**dc.publisher**
Label: Publisher
Hint: If the item has been published or accepted for publication, enter the publisher. If the item has not been published, enter "Virginia Tech." Examples: Wiley, Cornell University Press, Taylor & Francis

**dc.relation.ispartofseries**
Label: Series/Report Number
Hint: Enter the series and number assigned to this item. Examples: Virginia Cooperative Extension BSE-51NP, Airport Cooperative Research Program 124, TMC75-07-H-00008

**dc.identifier**
Label: Identifiers
Hint: If the item has any identification numbers or codes associated with it, please enter them. Examples: ISSN 0272-3638, DOI 10.1056/NEJMoa1510991, URL http://www.johncairns.net/ebook2.htm

associated: change messages.xml for series input-type #188

Modify common_identifiers value-pairs list (remove others)
- DOI (Digital Object Identifier) 
- Gov't Doc #
- ISBN
- ISMN
- ISSN
- URL (web link)
- Other

**dc.language.iso**
Label: Language
Hint: Select the language of the main content of the item. If the language does not appear in the list, please select 'Other'. If the content does not really have a language (for example, if it is a dataset or an image) please select "N/A." Examples: English, French, Chinese

Reorder common_iso_languages list (alphabetical)
- N/A
- English (United States)
- English
- Chinese
- French
- German
- Italian
- Japanese
- Spanish
- Turkish
- (Other)

REMOVE PAGE BREAK: PUT ALL ON ONE PAGE
REMOVE SUBJECT CATEGORIES LINK to custom controlled vocabulary=srsc

**dc.subject**
Label: Subject Keywords
Hint: Enter any keywords or phrases that describe the item's content. Enter each keyword or phrase separately, then click "Add." Repeat for all keywords or phrases. Examples: New River Valley, VA [Add], remote sensing [Add], photogrammetry [Add]

**dc.description.abstract**
Label: Abstract
Hint: Enter a brief summary of the item. Preferred length is a single paragraph or about 300 words, although you may enter an abstract of any length.

**dc.description.sponsorship** (make it a repeatable onebox) 
Label: Funding 
Hint: Enter the names of any funders and/or grant numbers. Enter each funder name or grant number separately, then click "Add." Examples: National Science Foundation [Add], NSF: DMR-01-02277 [Add]

**dc.description**
Label: Notes
Hint: Enter any additional information that will help describe the item.

**Remove from default submission form**
- dc.title.alternative
- dc.identifier.citation

**Notes from  #173**
I have added the moving image mapping to the MovingImageCustomSubmissionForm "form fields" sheet (Google Drive. Custom Submission Forms folder). I have separated out the fields that would be in the default section of the form (page 1) with those that are moving image specific (page 2). There are comments to highlight differences in the language between the existing form and the recommendations for moving images, as well as some questions.

remove file description

embargo: change to being a date box, why a date picker?
hint: make similar to date issued.
add a statement about embargoing
should require a year month day

keep embargo reason
Hint: Enter the reason for the embargo. Example: awaiting publicatio

**Comment by alawvt** [comment]
@mello99 and @amandafrench, it would be great if you could compare my notes above to yours and edit, as needed.

**Comment by amandafrench** [comment]
Please note that I did just find and push all my previous changes (which I hadn't finished making) to input-forms.xml and messages.xml to the configure-submission branch at https://github.com/VTUL/vtechworks/tree/configure-submission We can use that for reference if need be in our next meeting, and/or @AmberPoo1 can pull that branch and work on it once we give her the specifications. That branch is definitely not ready for a pull request, though.

**Comment by mello99** [comment]
Hi @alawvt , your notes on the common_types value-pairs list match mine. I guess the only concern  I have about our common_types value-pairs list is the integration with Symplectic; they have their own list of common value types, which I forgot to bring up during today's meeting, and they can be found in the [Symplectic Mapping on Google Drive ](https://docs.google.com/a/vt.edu/spreadsheets/d/1YAByXDYvHPaLW_H0acSBBnWovL8DhBCbhvNSnD0-cdw/edit?usp=sharing)(see the "DSpace Symp Elements Item Type Field Mappings" sheet - it's the 3rd one to the right). Something to think about.

As for the hints/labels above, there's one minor spelling error under "dc.publisher": "If the item has not **bee** published, enter "Virginia Tech". 

Another quibbly, nit-picky thing I noticed is that under "dc.date", we've written "A year is required, but month and day are optional. If the item has not been previously published, enter **current date**." I like "today's date" much better than "current date"; I just think it flows better and is more straightforward.

One last thing: I don't know if we discussed this and I was off in another world, but I think there's value in keeping the "dc.relation.ispartofseries" field; I've used it several times myself, and I think it could be potentially useful to people who are submitting their items to collections of related materials (for example, VTTI's NSTSCE reports). I also like the "Notes" field (dc.description) because it's a good place to store ancillary information that can't be captured in the other fields. That's just me, though, and I go crazy with metadata entry.

But yes, well done, Anne! All this time I thought that PLOS spelled its acronym "PLoS"; I quickly found out that wasn't the case!

**Comment by alawvt** [comment]
@mello99, thank you very much for the review and comments. I corrected the typo in the publisher hint. 

I agree that we should consider the Symplectic item type mapping. I think we'll need to test if not having the mapped type in the common_types list will be a problem for ingest. I'll add the test to the backlog. Those types on the Elements map, that are not in our current list are:
- Journal article (rather than Article)
- Conference
- Poster
- Performance
- Exhibition
- Composition
- Artefact
- Web page
- Patent
- Design
- Thesis AND Dissertation (rather than separate types)
- Scholarly edition
- Extension Publication
- Figure
- Fileset

For dc.date.issued, I also prefer today's date.

I agree that the Notes field is very useful. I think we could enlarge the hint to encourage submitters to use it well. I could go either regarding the series field.

**Comment by alawvt** [comment]
@amandafrench, thank you for the configure-submission branch. I am copying the hints, etc. to the spreadsheet.

**Comment by alawvt** [comment]
@amandafrench, do you want the examples in the hints italicized? (I have italicized the examples in messages.xml.)
@mello99 and @amandafrench, it would be great if you could compare my notes above to yours and edit, as needed.

**Comment by amandafrench** [comment]
@alawvt I'd prefer the examples in the hints not to be italicized, but it doesn't really matter. I did go over the notes above and altered the hints just a bit for Titles (I put in real publication titles by real VA Tech authors) and for Series / Report Number (I added a third one since the lack of balance disturbed me). I also changed "the current date" to "today's date" in the Date hint, as both you and @mello99 asked. 

Yes, we have spent a lot of time on the hints, but they are key, I think. :)

**Comment by amandafrench** [comment]
@alawvt Addendum: I meant that italicization doesn't matter _to me_, but since I've spent a lot of time on things that arguably matter as little, feel free to require italicization of the examples! Though I think it might be harder to put italics in the hints than in messages.xml; not sure html codes are allowed in item-submission.xsl.

**Comment by alawvt** [comment]
@amandafrench, thank you for reviewing these notes. I'll not specify italics for the examples in the hints. I have incorporated the changes into the MovingImageCustomSubmissionForm. This issue is continued by #198.

**Comment by alawvt** [comment]
Copied comment from https://github.com/VTUL/vtechworks/pull/213#issuecomment-203024204, 

Whoops, we forgot volume number and issue number - dc.identifier.volume, dc.identifier.issue -- we will probably need to add separate Identifier fields ...

options for volume and series fields
- create a onebox for each, with a separate hint and label
- add these fields to the existing identifier "qualdrop_value" form element and modify the associated hint to include volume and series instructions.

Check sponsorship in dc.description.sponsorship or dc.identifier field. The sponsor field in the revised submission form does not link grantor name and grant #  
Perhaps the "series" form field could be used for this since it relates two values. In dc.relation.ispartofseries is appears as "Virginia Cooperative Extension;BSE-51NP"

**Comment by alawvt** [comment]
added to backlog, to be resumed at a future sprint
