### ISSUE TITLE
BioMed Central Collection - Non-UTF-8 encoding issues

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#108]
Hi @amandafrench and @keithgee, the items in the BioMed Central collection (http://vtechworks.lib.vt.edu/handle/10919/18629) have a ton of non-UTF-8 encoding errors (especially HTML encoding issues), like `&#8472;` in place of ℘, `&#8805;` in place of ≥, and so on. I corrected most of these errors using LibreOffice ("Find and Replace"), but I don't know what else we can do since these items are imported via SWoRD. I just thought I'd let you know; thanks so much.

**Comment by alawvt** [comment]
@mello99, thank you for the report. Please add a backtick, `, before and after the character or HTML entity, so we can tell them apart, otherwise they will appear identical. I added the backticks to your report above. 

@amberpoo, also reported problems in the ETD collection with HTML entities like `&#8472`. We might look for a library or program to run the metadata through to convert these to standard UTF-8.

**Comment by amandafrench** [comment]
Related to #114.

**Comment by amandafrench** [comment]
I'll close this, since I want to see whether solving #114 (in other words, general HTML and character display issues in DSpace / Mirage2) will solve this. If not, we might have to configure or troubleshoot  SWORD.
