### ISSUE TITLE
Make sure SWORD puts DOIs in dc.identifier.doi

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#120]
Not in dc.identifier.uri, which should be reserved for the handle.

**Comment by keithgee** [comment]
I just pushed up a branch that has the 'gist' of the fix. But I'm having problems with the theme on my local and want to sort that out. 
Also, the fix needs some discussion.
- It's for SWORD 1.3, which is what BioMed Central uses
- The fix I have maps all of the URIs sent in the mets.xml to identifier.doi.  I think I need to make it more specific, in case other URIs, besides the DOI are ever included.

**Comment by keithgee** [comment]
Also, the 4 character change in the not-quite-complete fix truly represents hours of work. Testing was a challenge!  
 9ef49dc 
Edit: This is the initial, simple commit. Fixed later to put the URL in identifier.doi _only_ if it contains "dx.doi.org".

**Comment by keithgee** [comment]
I addressed the concern above and made the fix more specific. Branch biomed_central_doi_to_identifier_doi contains the fix that places url identifiers in "identifier.doi" if the url contains "dx.doi.org", and in "identifier.url" otherwise.

@amandafrench this may also cause changes in SWORD 2. I don't think that anything will break, but if there are problems with any SWORD integration projects you are doing, please let me know!

There is a pull request in place. Closing this issue.
