### ISSUE TITLE
SMTP server settings in build.properties

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#121]
So the build.properties file in the dspace root directory lists "smtp.example.com" as the SMTP server -- is that the correct SMTP server that DSpace actually uses? Surely not. 

Also, build.properties is tracked by version control; it's not ignored by .gitignore. Is the prod version of build.properties the same as the one in our local environments / GitHub? I want to set the SMTP server to smtp.gmail.com to avoid errors like today's with lib.vt.edu email (see Mattermost), but it requires authentication, so I'd have to enter a username and password for whatever GMail account I used (I figured we'd use vtechworks@vt.edu), which I don't want to make public on GitHub. Thoughts?

**Comment by kayiwa** [comment]
Hmmm. 

Hey @amandafrench I'd caution against using this. Certainly an edge case decision shouldn't be the driver. This source of this problem is being addressed. Some compromised machines in the library blacklisted lib.vt.edu for mail delivery. Your solution here wouldn't fix it because while it the smtp.gmail.com would send it the headers would say the source is lib.vt.edu and delivery would fail.

Cheers,
./fxk

**Comment by amandafrench** [comment]
Ah, good to know, @kayiwa. Thanks. Will close.
