### ISSUE TITLE
How long does it take for DSpace to generate item thumbnails? 

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#123]
Hi all, a professor submitted an image file to VTechWorks today and wanted to know how to create a thumbnail for it. 

I know that DSpace automatically generates thumbnails, but *how long* does it take for DSpace to generate a thumbnail? One day, two days, one week? Thanks so much for your help, and I hope all is well.

**Comment by keithgee** [comment]
One day.

**Comment by keithgee** [comment]
There's a command ```dspace filter-media``` that runs each night to build new thumbnails. @mello99, I just ran this manually, because it looked like it didn't run last night. I don't have access to see what time it runs (or else just don't know how to use the access).

It's also possible to make a custom thumbnail for filename.jpg, call it filename.jpg.jpg, and then upload it to the "THUMBNAIL" bundle in the web interface. I've done this in the past to switch them out for a few thumbnails that didn't look like good representatives of the associated items.
