### ISSUE TITLE
Need to configure search

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#15]
Ex: "Department of Energy" finds all results for energy - quotation marks don't work
[UPDATED] Ex: search for "LD5655.V855_1947.B695.pdf" in quotes pulls up numerous results instead of the single item with that PDF

**Comment by alawvt** [comment]
A search for "LD5655.V855_1947.B695.pdf"  (in quotes) should yield one result but instead yields 35,284 results! In quotes, this search would have yielded 1 result in version 4.

**Comment by alawvt** [comment]
I strongly suspect the searcher in version 5 is returning the "exact match" (as top result) plus 35,283 "similar" results, ranked in order of relevance.

This is probably due to the use of Solr for searching and the way the Solr searcher has been defined for the main search box.

Cheers,

Paul.

That does seem to be the case. Personally, I don’t find the other 35,283 results helpful. Hopefully we can configure it to be more like the old version.

**Comment by alawvt** [comment]
Related message  on DSpace-tech mailing list:  
[Dspace-tech] Search problem in DSpace 5.2 Mirage2, http://sourceforge.net/p/dspace/mailman/message/34407849/

**Comment by alawvt** [comment]
It looks like Texas A&M DSpace with Mirage2, https://oaktrust.tamu.edu/discover,  has the same issue. A search for "ESL-TH-91-05-03.pdf" yields 48,083 results.

**Comment by alawvt** [comment]
The DSpace repository, OceanDocs, from Belgium with Mirage2 (@mire?), http://www.oceandocs.org/discover, works as expected. A search for "AFFDU_36.pdf" yields one result. A search for AFFDU_36.pdf (no quotes) yields 5606 results. Hmmm.

**Comment by amandafrench** [comment]
I was trying unsuccessfully to find a repo with DSpace 5.x but *not* Mirage2 to pin down whether it was the theme or the code, but couldn't -- nice work! That repo runs on DSpace 5.1, so perhaps it's some change in the path from 5.1 to 5.2. Was also looking through the issues at http://jira.duraspace.org to see if it had been reported, but haven't found it yet. Does seem like it's the code and not the theme: I don't see how the theme would affect the search. And/or maybe it's just some config that is wonky.

**Comment by amandafrench** [comment]
Commit a0ff090d3486e456d698ef7dd15d2f007a79a3e9 should resolve this issue -- tested locally and it seems to. Grabbed from https://github.com/DSpace/DSpace/pull/1045 -- thanks @aschweer :)

**Comment by keithgee** [comment]
@alfrench, when you have a chance, can you show me what you've done to test this locally? I will add something to our Selenium tests to make sure that we don't break it in the future.

**Comment by amandafrench** [comment]
I did a basic search for "LD5655.V856_1990.X8.pdf" which found only the single item with that PDF locally, whereas on production it finds 240 items.

**Comment by alawvt** [comment]
This is great news.

**Comment by keithgee** [comment]
@alawvt, were you able to verify the test results of @amandafrench ?

**Comment by keithgee** [comment]
@amandafrench - I'm re-opening this issue; the fix doesn't work in production to resolve the issue as stated.

**Comment by keithgee** [comment]
@aschweer has also fixed overly-aggressive query escaping in a related commit, so we might need that, too.

**Comment by aschweer** [comment]
If you're using 5.3 then yes you need both commits from DSpace/DSpace#1045 - just the operator setting by itself won't work due to the escaping bug.

If you do get this to work using the two commits from DSpace/DSpace#1045, please also leave a comment on the PR :)

**Comment by keithgee** [comment]
@alaw @amandafrench I have deployed a hotfix to production in order to test the new git workflow, The hotfix includes the previous commit and the other commit from DSpace/DSpace#1045.

"LD5655.V856_1990.X8.pdf" finds 1 result
LD5655.V856_1990.X8.pdf finds 240 results , expected result is first

"flotation of fines" finds 10 results, expected result is second
flotation of fines find 183 results, expected result is eleventh

"Department of Energy" brings up 1123 results, but at a glance they seem related to Department of Energy

"LD5655.V855_1947.B695.pdf" brings up 1 result
"LD5655.V855_1947.B695.pdf" (in quotes) yields 1 result.

-fulltext:[* TO *] finds items without fulltext indexing.
environment:final (no space) yields no results
environment: final (space) yields 13974 results
"environment:final" 107 results
"environment: final" 107 results

@amandafrench should we close this issue and open others as appropriate?

**Comment by amandafrench** [comment]
@keithgee Yes, indeed! Great work -- thanks so much.
