### ISSUE TITLE
Improve display of CS Technical Reports

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#152]
See #151. @keithgee will look to see if can recover old DSpace 3 customizations.

**Comment by keithgee** [comment]
I've added two zip files to our Google Drive VTechWorks Team/technology area.
These are old themes from VTechWorks that both have customizations for Technical reports.
We can't use Chris's code directly, because,it's for themes older than Mirage 1 or Mirage 2, but it's well commented and could be a guideline.
- vtCSTheme is a theme that was applied only to the computer science technical reports( or maybe all computer science) collection/s.

-vtLibCms is what was deployed later, and applied to all collections. It tried to identify technical report items by looking for specific metadata quirks.

I personally like the vtCSTheme approach (separate theme for customizations that apply to only one collection) better, but there are advantages and drawbacks to both. 

A word of warning, too - xmlui was designed for this sort of thing - giving custom themes to specific collections - but it can be a rabbit hole to try and apply endless customizations that apply only to a small percentage of the collection. Be careful! ;)

**Comment by keithgee** [comment]
Also, the only display related item  mentioned in #151 that we haven't already done in a previous commit is this:

```
 what we need to see is the TR number listed in all the "summaries" of wild card searches.
 Each "item" shows the title, authors, and year, but NOT the TR number 
```

@alawvt @amandafrench is this the only display change that is required for this open issue?

**Comment by alawvt** [comment]
@keithgee, thank you for finding those old themes. Yes, the TR number displayed in the search results and when browsing the collection. They also wanted the browse to be in reverse chronological or TR number order.

@AmberPoo1, these old themes were implemented as overlays of the dspace-xmlui module, rather than as overlays of the dspace-xmlui-mirage2 module. They would have been in dspace/modules/xmlui/src/mail/webapp/themes/. See especially vtCSTheme/lib/xsl/aspect/item-list.xsl, lines 221-229.
