### ISSUE TITLE
7 items in College of Science don't have attached files

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#161]
See recent items at http://vtechworks.lib.vt.edu/handle/10919/5553 

Example: http://vtechworks.lib.vt.edu/handle/10919/64239 Says it was deposited 11/29/15 but doesn't say who by. Item ID 74417,

**Comment by amandafrench** [comment]
See also http://vtechworks.lib.vt.edu/handle/10919/64238 in College of ENgineering - these might be related to #159, but maybe not.

**Comment by amandafrench** [comment]
Also one in CLAHS: http://vtechworks.lib.vt.edu/handle/10919/64232

**Comment by amandafrench** [comment]
By the way, you don't need to work on this until Monday, @keithgee.

**Comment by mello99** [comment]
The plot really thickens here, @amandafrench and @keithgee . 

Those items that have missing files? Those are Web of Science items that I uploaded on November 28, 2015. 

I initially thought that I'd goofed and uploaded only the spreadsheets without uploading the associated files, but that doesn't appear to be the case. If you look at the attached ZIP file, you'll see the spreadsheets that I created and uploaded on 11/28/2015 (I also saved each of the import maps). If you search for the titles in those spreadsheets in DSpace, you'll find the records with the associated files, but you'll also find some records with no files at all. The records that have no files appeared on 11/29/2015; I don't know how this happened because I'm almost positive I didn't re-upload them and can't think of a reason why I would. 

Here's where it gets really interesting/messed up (depending on your perspective): most of the Web of Science uploads I've looked at thus far are associated with the mismatched files and metadata from the College of Science. Just search for the following titles in VTW and you'll see what I mean (this isn't all-inclusive; see the spreadsheets for more details):
- "Self-Association Is Required for Occupation of Adjacent Binding
  Sites in Pseudomonas aeruginosa Type III Secretion System
  Promoters"
- "Role of YpeB in Cortex Hydrolysis during Germination of Bacillus anthracis Spores" - appears in 4 different articles, 3 of which have mismatched metadata and files"
- "A CRISPR with Roles in Myxococcus xanthus Development and Exopolysaccharide Production"
- "Biochemical Characterization of a Dihydroneopterin Aldolase Used for Methanopterin Biosynthesis in Methanogens"

What...a...mess... I hope this helps us get to the bottom of things (please enjoy your weekends, though; don't mind my craziness!).

[2015_11_28_VTW_Files_Issues.zip](https://github.com/VTUL/vtechworks/files/83516/2015_11_28_VTW_Files_Issues.zip)

**Comment by keithgee** [comment]
Yes, that's helpful Melissa!

**Comment by keithgee** [comment]
The very first item id that Amanda has given, 74417, does appear in the CSV file that's in our "Metadata" directory. But the row only has some of that metadata. There was a suggestion by @alawvt that some of these large files might be parsed incorrectly.

**Comment by keithgee** [comment]
@mello99, I looked at the log file from November 28 2015, which was the Saturday of Thanksgiving weekend. It looks to me like you may have uploaded these items twice.

I looked at the first and last example you gave in your comment. In each case, there are currently three items with the title.
1. An item with the correct file attached, created at 4:53PM 
   [I think you want to save these]
2. An item with no file attached, created at 11:51 PM
   [I think you want to delete these items with no attached files]
3. An item with a file that doesn't correspond to the title, created on some other date but modified recently
   [These should be cleaned up with your work on issue #159]

So, it looks like these items were created twice on November 28 as part of CSV uploads, and the items that don't have any attached files should be deleted. The ones that have files attached, whether correct or incorrect, should be saved. Does that make sense?

**Comment by mello99** [comment]
I'll go ahead and delete the items with no files, but I SWEAR I didn't go back and reupload everything after getting a successful upload message (see the attached ZIP file for the import maps). 

Maybe I uploaded the items a second time after getting an UNSUCCESSFUL upload message, or a blank screen altogether (that happens sometimes - I don't get notified that the items have been successfully uploaded), but that would have been done immediately after the first upload attempt. 

I also would have waited for the items to appear in VTW instead of reuploading them (that is if I DID get a successful upload message the first time) because I know it can take DSpace a few days to re-index things. 

A reupload 7 hours after the fact, though? And why does DSpace say the items were uploaded on 11/29 if they were uploaded on 11/28 (even at such a late hour)? That's so weird... and frustrating. I'm starting to doubt my own sanity.

Below is a list of the items that were deleted, since they were duplicates and had no files. There were 12 altogether.

[Deleted_Duplicate_Items.csv.zip](https://github.com/VTUL/vtechworks/files/83760/Deleted_Duplicate_Items.csv.zip)

**Comment by mello99** [comment]
@keithgee , if you have time, could you look at my VTechWorks submissions page sometime next week? I ask because I noticed that one of the items that was uploaded on 11/28 was NOT reuploaded on 11/29, despite the fact that the 3 other items on the same spreadsheet WERE reuploaded on 11/29. I have no idea what happened.

**Comment by keithgee** [comment]
The duplicates were deleted by @mello99. I'm closing this issue per our discussion at the stand-up meeting.
Closing.
