### ISSUE TITLE
Check the status on vtechworks.lib.vt.edu for requesting a document

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#189]
Please check the latest configuration.

**Comment by AmberPoo1** [comment]
On http://vtechworks.lib.vt.edu/, when ordinary users or a guest access restricted item off campus, the page shows:
![1](https://cloud.githubusercontent.com/assets/13734326/12877570/69ad3228-cde3-11e5-9fd6-c02d274ed878.png)

Administrators, VPN guest and VPN ordinary users can access  restricted item directly.

**Comment by alawvt** [comment]
I used free-proxyserver.com to access http://vtechworks.lib.vt.edu/handle/10919/53800. I got the slightly different screen, 
![request_item_from_off_campus_20160208](https://cloud.githubusercontent.com/assets/13037168/12889108/7019d842-ce4b-11e5-88a5-5be67d36c264.png)

**Comment by keithgee** [comment]
Jing was already logged-in as a user on the screen that she shared.

**Comment by amandafrench** [comment]
True, @keithgee, but the request form is supposed to be turned off for all off-campus users, whether logged in or not, because I commented it out in #154. Administrators would be able to see the file, of course, when logged in, even off-campus, but they wouldn't get the request form. 

In any case, although we do have to make sure that changes to dspace.cfg get deployed somehow, there's not much point in turning off the requests at this point because we'd just have to turn them on again in a few days.

**Comment by amandafrench** [comment]
@keithgee Although perhaps you were responding to @alawvt's comment that the screen she got is "slightly different" than the one @AmberPoo1 got. The only difference (apart from screen resolution) is that the second screenshot adds an invitation to log in.

**Comment by amandafrench** [comment]
This isn't really an issue any more; the next time we deploy, though, I'll be sure to remind @kayiwa to compare the dspace.cfg file on production with the one in the release.
