### ISSUE TITLE
In submission form, modify the embargo step

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#193]
Research the embargo date field: is it a date picker or should it be changed to a date box (but needs to have a date, not year requirement.
Hint: make similar to date issued.
add a statement explaining what the embargo does.

keep embargo reason
Hint: Enter the reason for the embargo. Example: awaiting publication

**Comment by amandafrench** [comment]
One addendum: it might not be a good idea to make it similar to Date, since an embargo date (surely?) must have YYYY-MM-DD, whereas Date only needs a YYYY. But I'd be interested to know what the heck happens to embargoed items when only YYYY or YYYY-MM is specified; when does the embargo lift? Needs testing. If the lack of DD messes up the embargo lift date, this might be worth contributing to DSpace.

**Comment by alawvt** [comment]
The embargo field has a date picker which results in a date text stream, e.g. 2016-02-09, in the text box. One can backspace and remove the month and date leaving 2016-02 or 2016. On vtechworks.dev, I created an [embargo date test item](http://vtechworks.dev.lib.vt.edu/handle/123456789/64419), with files with various embargo release dates. The file that was submitted with an embargo date of 2016-03 was changed by the system to a release date of 2016-03-01. The file that was submitted with an embargo date of 2016 was changed by the system to a release date of 2016-01-01. 

Side note: Unlike embargoed ETDs outside of VTechWorks, embargoed file names are viewable. If you click on one, you get the log in screen.

@amandafrench, given this, do you want to alter the labels and/or hints?

**Current**
Label: Embargo until specific date 
Hint: The first day from which access is allowed. Accepted format: yyyy, yyyy-mm, yyyy-mm-dd

Label:  Embargo reason
Hint: The reason for the embargo, typically for internal use only. Optional.

**Comment by amandafrench** [comment]
Ah, so that's good to know that the date picker and dates are working with the current field setup. I think it's probably not worthwhile to change the input type for either the embargo date or the "Date issued" inputs. Here are new labels: 

Label: Embargo this file until a specific date
Hint: To keep this file private until a certain date (embargoed), enter the date on which it should become public. Each file you add can have a different embargo period. Note that the item record with such information as title, author, and abstract will be public: only the associated file will be inaccessible. Use the pop-up calendar to pick a date or type the date in manually. Examples: 2020-04-01 (file will become public on April 1, 2020); 2020-04 (file will become public on April 1, 2020), or 2020 (file will become public on January 1, 2020). 

Label: Embargo reason
Hint: The reason you would like the file to remain private for a certain period (embargoed). The embargo reason is not shown anywhere in the public record of the item: it is for administrator use only. Examples: Awaiting publication, Applying for a patent, File contains personally identifiable information.

**Comment by alawvt** [comment]
@AmberPoo1 please modify the embargo fields in the submission form to the labels and hints listed in the comment above.

**Comment by amandafrench** [comment]
Done: being reviewed
