### ISSUE TITLE
Missing rubygem when running Maven

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#196]
```
[ERROR] Failed to execute goal on project xmlui-mirage2: Could not resolve dependencies for project 
org.dspace.modules:xmlui-mirage2:war:5.5-SNAPSHOT: Failure to find rubygems:rb-inotify:gem:0.9.6 in
 http://rubygems-proxy.torquebox.org/releases was cached in the local repository, resolution will not be 
reattempted until the update interval of rubygems-release has elapsed or updates are forced -> [Help 1]
```

I searched for `rubygems:rb-inotify:gem:0.9.6` and found an issue in [Stack Overflow](http://stackoverflow.com/questions/35270637/rb-inotify-0-9-6-gem-missing-from-rubygems-org), from this morning and in  [Redhat bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1305192) from Friday https://bugzilla.redhat.com/show_bug.cgi?id=1305192

**Comment by alawvt** [comment]
There is a discussion of this on the [DSpace Tech Support listserv](http://dspace.2283337.n4.nabble.com/DSpace-5-4-Rebuildprocess-with-maven-td4680821.html).

**Comment by AmberPoo1** [comment]
@alawvt, I found the same problem yesterday. It was caused by the maven dependency RUL of rubygems which is no longer available. The problematic code is in the pom.xml under vtechworks/dspace/modules/xmlui-mirage2/pom.xml. Code snippet：
`<repositories>
        <repository>
              <id>rubygems-release</id>
              <url>http://rubygems-proxy.torquebox.org/releases</url>
             </repository>
  </repositories>`

Currently, we can compile dspace using the following method to avoid this problem:
1. Make sure all the mirage2 prerequisites are installed locally(Maybe re-installing these prerequisites are neccessary), following this instructions:
https://github.com/DSpace/DSpace/tree/master/dspace-xmlui-mirage2#installation
1. Then run this maven command, it will compile successufully:
   mvn package -Denv=dspacedevvm.local.vt.edu -Dmirage2.on=true -Dmirage2.deps.included=false

**Comment by alawvt** [comment]
@AmberPoo1, thank you very much figuring this out. I was able to get Maven to work this way.

**Comment by kayiwa** [comment]
Has this been tested further? mvn runs successfully but it still fails to build local 
`[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] DSpace Parent Project .............................. SUCCESS [  0.626 s]
[INFO] DSpace Services Framework :: API and Implementation  SUCCESS [  2.102 s]
[INFO] DSpace Kernel :: API and Implementation ............ SUCCESS [  5.810 s]
[INFO] DSpace Addon Modules ............................... SUCCESS [  0.028 s]
[INFO] DSpace Kernel :: Additions and Local Customizations  SUCCESS [  1.073 s]
[INFO] DSpace XML-UI (Manakin) ............................ SUCCESS [  3.146 s]
[INFO] DSpace XML-UI Mirage2 Theme ........................ SUCCESS [  0.136 s]
[INFO] DSpace XML-UI Mirage2 Theme :: Local Customisations  FAILURE [  7.738 s]
[INFO] DSpace XML-UI (Manakin) :: Local Customizations .... SKIPPED`

**Comment by alawvt** [comment]
Yes, I am able to run it  by installing the dependencies for Mirage2, as @AmberPoo1 described and manually downloading the gem, as described in the linked DSpace Tech Support issue.

**Comment by amandafrench** [comment]
If possible / necessary, I'd like us to fix this upstream in DSpace core, if it hasn't already been fixed by someone there. Assigning it to @AmberPoo1 to look into.

**Comment by amandafrench** [comment]
Or even in the Maven project! https://maven.apache.org/ But not if it will take a lot of time.

**Comment by alawvt** [comment]
This seems to have been fixed.
