### ISSUE TITLE
Test giraffe+ sprint changes on vtechworks.pprd

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#230]
Note: After we have deployed to vtechworks.dev, add tests from Google Drive...DSpace_5_5_Testing, #222, to testing list for this sprint.

**Comment by alawvt** [comment]
I have finished testing on vtechworks.dev.  @amandafrench, please deploy to pprd.

**Comment by amandafrench** [comment]
I've merged the changes into vt_5_x_pprd_deploy, but I want to check to make sure we won't overwrite the Elements changes on pprd before I ask for it to be deployed. Might make sense to just do another deployment to dev and send it all along to pprd and prod.

**Comment by keithgee** [comment]
Amanda, thanks for your care. I'm thinking that you should go ahead and ask for these to be deployed to PPRD. It _will_ temporarily overwrite Elements changes, but the README.md file for the elements_install_scripts project in our GitLab names one script that I will run to restore the Elements repository tools.

This is a great opportunity for me to test that script on a server that's configured like production. If it doesn't work perfectly, no need to worry because I've just made sure that all of the relevant files are in source controls. I'll have the Elements tools installed and functioning again quickly. It sounds scary, but my thinking is that it's better to figure out any problems with Elements deployment/redeployment now. It will make production deploys go smoother, and will help me to talk to Francis when we all meet about this..

Thanks!

**Comment by amandafrench** [comment]
Okay, @keithgee, will do! Was just about to contact @kayiwa about that.

**Comment by alawvt** [comment]
@amandafrench, I have tested the changes on vtechworks.dev and they are ready to deploy to vtechworks.pprd.

**Comment by amandafrench** [comment]
Great, thanks! Will create the branch.

**Comment by alawvt** [comment]
I see the non-Elements changes on pprd.

**Comment by alawvt** [comment]
I have tested the non-Elements changes on pprd and they all pass. When Elements testing is finished, the changes can be deployed to production.

**Comment by amandafrench** [comment]
Great, thanks, @alawvt!

**Comment by amandafrench** [comment]
The Elements (hamster) changes have been tested on pre-production: and all are ready to be tested on production. We can't really do much testing of the Elements crosswalk on production, since @mello99 doesn't have access to it and since in any case we don't want to create a bunch of dummy items, but I've done enough testing to pass it. (There is a spreadsheet of what I've done in the "Testing" folder on Google Docs.) Therefore it's only non-Elements related changes that need to be tested on production.

**Comment by alawvt** [comment]
I have tested the non-Elements changes on production and they all pass.
