### ISSUE TITLE
List of metadata elements in config file?

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#253]
Hi, @keithgee , where can I find a list of the metadata elements in the DSpace config file? I looked in the "config" files on GitHub and couldn't find what I was looking for. I just wanted to add all of the remaining fields in the Elements schema to the config file to prevent possible duplication. Although doing this would add several fields that we might not use, I think it would be helpful to add these fields anyway **in case** we choose to use them later on. I can do this if possible. Thanks.

**Comment by keithgee** [comment]
@mello99 I've given you access to a project called "elements_install_scripts" on our GitLab service. The configuration parameter you are looking for is called publications.metadata.authority-list, and it is in a file called "append_to_dspace.cfg" in that GitLab project.

These configuration parameters will move to dspace.cfg in GitHub after the initial installation, because we now have permission to do so from Symplectic, but I think that the way our deployment process works the initial install will go smoother with the parameters still in GitLab. So go ahead and change them there if you need to do so.

Thanks!
