### ISSUE TITLE
Elements crosswalk (maybe) minor issue - invited talks

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#259]
For "Presentation" item types, there's a checkbox in Elements that asks whether the presentation was invited. This info gets pulled into the description.notes field, but in an ugly way, as follows: 

> dc.description.notes  true (Invited?)

When the "Invited" box is left unchecked, the field reads "false (Invited?)".

Don't know whether it's possible to fix this in the crosswalk: can report as minor issue to Symplectic if necessary.

**Comment by mello99** [comment]
Hi, @amandafrench , this is something we can fix. I actually added that customization because I wanted to provide more contextual information in the "dc.description.notes" field; a simple "true" or "false" wouldn't tell the user very much (and there's no custom Symplectic field for invited publications, though we could add one). 

That being said, I can create a custom Symplectic field for invited publications and map text in "c-invited" to that field. We could also get rid of this mapping altogether and not deposit input for "c-invited" into VTechWorks.

Another option would be to convert the "true" or "false" output to another text string, which Andrew was able to do for the Creative Commons licensing text. I'd love to do this - it just might take some time to experiment with.

**Comment by amandafrench** [comment]
Personally I think that if the box is checked, we should get the string "Invited" in the notes field; if it's not checked, we should either get no data (for preference) or a string like "Not invited" (though that's a bit insulting). Will assign to you: you should probably enter any outstanding crosswalk issues here individually, too, though they're all covered on the task board by a single post-it!

**Comment by mello99** [comment]
Added some code that will hopefully achieve this (see [this commit](https://github.com/VTUL/vtechworks/commit/999cc9334be03fc9c31115cf714614ed232176c3)): 

`<crosswalks:dictionary dspace="c-invited" mapped-only="true">
   <crosswalks:entry elements="true" dspace="Invited publication" />
 </crosswalks:dictionary>`

The rationale behind this code is that if there's no mapping for "false" (that is, if the "c-invited" box is unchecked), no data will be transmitted to VTW. I hope this works!

**Comment by amandafrench** [comment]
Great! Don't forget that you'll have to submit a pull request to merge the elements_dspace_xslt_changes branch into the main branch before the code can be deployed at the end of the sprint, @mello99. If you don't have any other changes to make to the crosswalk, you can do that now.
