### ISSUE TITLE
Request to review documentation in Wiki

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#26]
@keithgee, I would appreciate it if you would review the following pages that I edited after our meeting this morning.
https://github.com/VTUL/vtechworks/wiki/2.-Making-changes-on-the-local-development-environment  
https://github.com/VTUL/vtechworks/wiki/3.-Issue-pull-request-to-Github  
https://github.com/VTUL/vtechworks/wiki/3.-Pushing-local-changes-to-GitHub  
https://github.com/VTUL/vtechworks/wiki/Git-Workflow  
https://github.com/VTUL/vtechworks/wiki/Project-Maintainer-Instructions  

Thanks, @alawvt

**Comment by alawvt** [comment]
I reviewed the "feature branch/review/merge" video and think it is worth recreating with the new branch name, vt_5_x_dev. In the meantime, I transcribed the instructions in the video to the corresponding wiki pages.

**Comment by keithgee** [comment]
@alawvt I will have a look.

**Comment by keithgee** [comment]
@alawvt 

https://github.com/VTUL/vtechworks/wiki/2.-Making-changes-on-the-local-development-environment
Looks good. 

- maven commands don't fit in the wiki display on my screen. let me know if you have a solution, I need a wider display for a document that I'm working on as well.
- asking to type the" vagrant up" command assumes that the virtual machine is not already running, but perhaps that's okay because the command won't cause any problems

https://github.com/VTUL/vtechworks/wiki/3.-Issue-pull-request-to-Github
This link doesn't work for me. Not good.

https://github.com/VTUL/vtechworks/wiki/3.-Pushing-local-changes-to-GitHub
This link doesn't work for me.

https://github.com/VTUL/vtechworks/wiki/Git-Workflow
Very good. 

- I would remove the "Other Options Considered" section, as it is no longer relevant.
- I plan to separate the Project Maintainer Instructions page into separate sections so that I can link from other documents to smaller topics, so I'll need to fix broken links or do it in a way that the links aren't broken. 


https://github.com/VTUL/vtechworks/wiki/Project-Maintainer-Instructions
 - As I mentioned, I'm going to break this down into smaller sections (on separate pages)
 -  For the "Manage Pull Requests" section, we might need specific instructions for "Pull the branch to your local machine to test it".
- I don't understand "There is a form to correspond with the requester if need be."
- It might be nifty to have screenshots for when people are instructed to use the web interface to interact with GitHub.

And then, we started on [another page](https://github.com/VTUL/vtechworks/wiki/Workflow-Summary)  to give specifics about how our customized Git Flow workflow works with our Agile processes. The page will also link to other topics.

- I'm having a difficult time getting the image to show at an appropriate, readable size

We're on our way to being better!

**Comment by alawvt** [comment]
@keithgee, thank you for your review. I made some changes based on your comments. I agree that certain sections, particularly the project maintainer instructions, need more detail.
