### ISSUE TITLE
Remove automatically added rights statements from OMALS and NDLTD submission forms

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#276]
Remove automatically added rights statements as displayed in http://vtechworks.lib.vt.edu/handle/10919/70992?show=full 

Only Creative Commons data should be displayed.

**Comment by amandafrench** [comment]
Take out the following: 
- In Copyright (InC)
- This Item is protected by copyright and/or related rights. Some uses of this Item may be deemed fair and permitted by law even without permission from the rights holder(s). For other uses, you need to obtain permission from the rights holder(s).
- http://rightsstatements.org/vocab/InC/1.0/

**Comment by alawvt** [comment]
also remove those rights statements from recent items in each collection.

**Comment by alawvt** [comment]
In the NDLTD collection, I left the rights fields for http://hdl.handle.net/10919/65154, since I loaded it.

In the OMALS collection, I removed the InCopyright fields for:  
- http://hdl.handle.net/10919/70992  
- http://hdl.handle.net/10919/70991  
- http://hdl.handle.net/10919/70990  
- http://hdl.handle.net/10919/70989  
- http://hdl.handle.net/10919/70849

**Comment by amandafrench** [comment]
Related to #267.

**Comment by alawvt** [comment]
Resolved with PR #333.
