### ISSUE TITLE
Submission form is broken after installing Elements

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#282]
The submission form works after commit https://github.com/VTUL/vtechworks/commit/cda900e37563f9b6d56b692c956cfc81b7104602 (5/3).

The submission forms does not work after the next commit, which added the Elements configuration, https://github.com/VTUL/vtechworks/commit/574d07777825f150629e33ffa35f19ff12eeb6fb (5/9).

I would not push the Irish Setter sprint commits until we get this resolved. I will look at it and hopefully, @keithgee will see it, too.

This commit adds configuration changes to the dspace.cfg and doesn't change the submission form template directly.

**Comment by alawvt** [comment]
Need to gather data:
My understanding is that Elements servers are connected to both pprd and dev. The submission forms in both pprd and dev work. I can not see the dspace.cfg code for these two repositories. It would be good to compare them to the one here.

**Comment by alawvt** [comment]
In the most recent version (commit https://github.com/VTUL/vtechworks/commit/0f360a9e76c712307c5579d10a34566919bca436) of dspace.cfg, row 751, if I delete ", elements" the submission form works, but probably Elements does not.

Submission form does not work:

```
event.dispatcher.default.consumers = versioning, discovery, eperson, harvester, elements
```

Submission form does work:

```
event.dispatcher.default.consumers = versioning, discovery, eperson, harvester
```

I was able to compare dspace.cfg to the one in pprd. The one is pprd is very much like this one. The event.dispatcher.default.consumers does list elements.  
@keithgee did mention needing to do something more than just running the script to get Elements to work with DSpace. I don't know if this is affected by that.

**Comment by keithgee** [comment]
@alawvt, which system is this problem happening on? LDEs? Dev? Pre-production? Production?

Thanks!

**Comment by keithgee** [comment]
Based on comments in this GitHub issue and others, this problem is currently only happening on LDEs, and not Dev, Pre-production, or production.

The line that is causing the problem, 

```
event.dispatcher.default.consumers = authority, versioning, discovery, eperson, harvester, elements
```

is already installed in dev, pre-production, and production as part of the Elements install, and is not causing issues. [Though note that authority was still turned on in production]. In fact, the "elements" consumer needs to be in the line for elements to work properly.

The commit was to make sure that our configuration file was up - to -date with what's in production. Unfortunately, though, this particular parameter is different for systems that don't have Elements installed(which is, in our case, the LDEs). The problem won't occur on old LDEs, but some LDEs that have been provisioned newly after the commit will have the problem, and the "elements" consumer should be removed from the line in the LDEs.

@alawvt, you've already found the fix for the new LDEs - just remove the elements consumer from the line and everything should work as normal. For our dev, production, and pre-production systems, though, the elements consumer needs to stay on the line so that Elements deposits work.

Because the line differs on some systems, it should be parameterized, just as database password and hostname information is parameterized. I don't have time to do this now, but I added it to the backlog in case someone else wants to tackle it.

I put a note in our [LDE setup instructions](https://github.com/VTUL/vtechworks/wiki/1.-Setting-up-a-local-development-environment-on-Mac) to change the line, until we can parameterize it.

**Closing

**Comment by alawvt** [comment]
I have submitted a TeamDynamix request to treat this setting as a parameter for LDEs, so the submission form and other events in the LDE will work. In the meantime, we can each omit this "elements" from dspace.cfg on our LDEs. I will put a note about this temporary fix in the README on GitLab and GitHub.

**Comment by amandafrench** [comment]
This is superseded by #288, correct? If not, feel free to reopen.
