### ISSUE TITLE
Recreate video playback feature on item display page

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#31]
A very popular and much-requested feature. I looked for documentation related to it in Redmine, but didn't see any -- will trust @keithgee to find and document it. 

Might actually be good to create a separate GitHub repo for this, @keithgee, so you can abstract it enough to submit to DSpace core. I see you've got a fork of VTW, but if you forked DSpace core to your own profile and developed there, you could submit it to us both ... up to you.

**Comment by keithgee** [comment]
I have submitted a pull request to resolve this issue.

@amandafrench, what sort of documentation would you like? I've previously placed multiple documents related to the previous implementation in our VTechWorks group folder. I may already have something that matches what you're looking for, and can move it to your preferred location. If there's something missing, I'll add it. Let me know what documentation is needed.

Amanda, I think I really should be involved in whatever video project there is for DSpace by looking at the possible implementations, finding a solution that will work for many people, including us, but it's a matter of actually having the time. Having this in our repository, which currently isn't a fork, won't be a difficult complication for submitting something back to DSpace core. The part that I've done to save us time during upgrades - implementing this as maven overlays - might actually slow down submission to the DSpace project slightly, but I've carefully marked our changes so that it won't be a major issue.

**Comment by amandafrench** [comment]
Thanks, @keithgee! I think you can save documentation for after the sprint, if you like, or include it in a future sprint. Though if you want to just copy-paste what you have already on the wiki as a placeholder, that'd be fine. I'd need to learn more about the feature before I know what documentation it needs, though as I mentioned it's probably good to list what files it affects so that it can be easily recreated in future upgrades and by different DSpace projects. 

You can save abstracting it for DSpace core till later, too. I'm just thinking about your reputation -- the time when everyone will say, Ooh, nice work, @keithgee.
