### ISSUE TITLE
Put individual download stats on simple and full item views

### ISSUE THREAD

**Issue by pgray64** [VTUL/vtechworks#317]

**Comment by amandafrench** [comment]
You can see an example of the kind of thing we want at another DSpace instance run at the University of Maryland -- it says "No. of downloads": 
![screenshot 2016-07-06 13 18 21](https://cloud.githubusercontent.com/assets/227453/16627669/4099957a-437c-11e6-90e0-7f569da0cec5.png)

Their GitHub repo is at https://github.com/jennielevineknies/drum so there might even be some code there you can use. I'd like it to be a bit more prominent than theirs, though. If it can be close to where the altmetrics badge appears for items that have it, that'd be ideal, but it might be tough, and it's not important (see http://vtechworks.lib.vt.edu/handle/10919/23885 for an example of an item with altmetrics data and therefore a badge). 

Note that although the issue did say to put it on simple (short) item view, it should be on full view as well. Also, there's a distinction between item record views and file views: if possible, I'd like both stats to appear, and for all associated files. Language and display something like this: 

## **Item visits:** 460

## **Gilbertson_Mutant.pdf visits:** 170

It'll be a little hard because the sidebar is so narrow, but do what looks good to you and we'll review it. If we can even get just the "Item visits" like DRUM that'll be good.

**Comment by pgray64** [comment]
Unfortunately that repo has .gitignores in quite a few places and uses DSpace 1.7. Based on the Dspace docs, I'll have to add XSL to the item view that queries SOLR directly.

**Comment by pgray64** [comment]
@AmberPoo1 Do you know if item visit counts and file download counts are already accessible as variables in item-view.xsl?

If there isn't, might have to write XSL that queries SOLR directly. Don't know how the UMD guy did it, because the relevant directories in his have .gitignores.

**Comment by AmberPoo1** [comment]
@pgray64 I agree with you that writing some XSL to query SOLR statistics is needed. There are some online resources might be useful.

https://wiki.duraspace.org/display/DSPACE/Solr
"Querying Solr from XMLUI"

https://wiki.duraspace.org/display/DSDOC5x/SOLR+Statistics
Especially,  in the sections: "2.1.4 Item home page" and "10 Custom Reporting - Querying SOLR Directly"

And DRYAD's documenatation also gives out some information on this functionality:
http://wiki.datadryad.org/Statistics_Technology

**Comment by pgray64** [comment]
I believe the current UMD DSpace repo is https://github.com/umd-lib/drum - found their custom item-view code.

**Comment by pgray64** [comment]
**For file download count**
UMD's modification to java source is just a SOLR query, so can do that in our XSL instead. 
Java to convert to XSL

```
SolrLogger.queryTotal("id: " + bitstream.getID(),
                    "type: " + Constants.BITSTREAM + " AND -isBot:true")
                    .getCount();
```

https://github.com/umd-lib/drum/blob/drum-master/dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/ItemAdapter.java

**Comment by amandafrench** [comment]
Putting this on hold for now.

**Comment by alawvt** [comment]
@pgray64 reports that he has made progress on creating the SOLR query but needs to figure out how to get and use the Item ID from the XMLUI.

**Comment by pgray64** [comment]
Finished the individual stats - will test it more and create pull request on Friday.

**Comment by amandafrench** [comment]
@pgray64 Great, thanks!

**Comment by pgray64** [comment]
PR #427 implements this

**Comment by pgray64** [comment]
Note for testing: SOLR caches things, you can restart tomcat `sudo service tomcat7 restart` to see fresh stats.

**Comment by alawvt** [comment]
completed
