### ISSUE TITLE
Enable Content Type stats and standardize Content Types

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#321]
There's a thread at http://dspace.2283337.n4.nabble.com/DSpace-5-x-Legacy-Statistics-Item-Type-Breakdowns-td4676851.html that is relevant -- currently, the administrator view of statistics includes Content Types, but it doesn't seem to be accurately tracking how many items of each content type there are in the repository as it should. 
![screenshot 2016-07-06 13 44 33](https://cloud.githubusercontent.com/assets/227453/16628496/f91717a0-437f-11e6-92b4-d42695503570.png)

This might be mostly a configuration issue, but it might also have to do with the values that are in the dc.type field. @mello99 is going to work on creating a set of standards for content types this month, so you and she might need to confer about this, @pgray64.

**Comment by pgray64** [comment]
Yep, the three displayed content types are the only ones listed in dstat.cfg - just a matter of adding the types in use (and removing ones that aren't). 

Its likely case sensitive though, and I know not all items are using consistent capitalization. The SQL function I put on the [gitlab wiki](https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SQL_for_DSpace) could fix that for existing items.

**Comment by pgray64** [comment]
For the smaller database dump, after converting all item type values to sentence case, there are 85 distinct item types. 

(Via this SQL query)
`select distinct text_value from metadatavalue where metadata_field_id=66;`

**Comment by alawvt** [comment]
We do have 3 "Preprint," http://vtechworks.lib.vt.edu/search-filter?field=type&starts_with=p, so that statistic is correct, . We have lots of "Thesis" and "Dissertation," which are not showing up.  
- DIssertation (1)
- Dissertation (1070)
- dissertation (8192)
- Dissertation, Reproduction (Electronic) (247)
- Thesis (3938)
- thesis (12274)
- Thesis, Reproduction (Electronic) (88)

You could test whether the "or" in `item.type=Thesis or Dissertation` is causing the problem.

There are some old, but probably still ok instructions for configuring these legacy stats in [DSpace How-To Guide](https://www.ideals.illinois.edu/bitstream/handle/2142/1043/DSpaceHowToGuide.odt.pdf?sequence=5), pages 35-37.  You might look if other DSpace repositories have customized this file in their GitHub repositories.  

There are some old notes on the DStat package in the DSpace wiki at [DstatPackage](https://wiki.duraspace.org/display/DSPACE/DstatPackage).

**Comment by pgray64** [comment]
The config file for content-type stats doesn't interpret booleans and is also case sensitive. I could try to fix that, but it'll likely be java changes since its with legacy stats.

**Comment by alawvt** [comment]
Thank you for testing this. Since these legacy stats seem to no longer be actively developed and they rely on logs which we no longer keep in full on our servers, I'd be inclined to just use them as-is.

**Comment by amandafrench** [comment]
Thanks to @mello99 we do now have a sense of what we want our Content Types to be (see spreadsheet at https://docs.google.com/a/vt.edu/spreadsheets/d/1Ul-hTkUt5TFJKPTOIXD27CmLagKWaBDomNLsKcBL4Xw/edit?usp=sharing ), so I went ahead and did this, though we won't deploy till next month. Created pull request at #347 to address this and assigned to @pgray64 for testing. Once it passes, we can close this issue. 

Obviously the counts will still be off until we clean up the data, but we can do that later. We'll test the SQL functions @pgray64 wrote next month. Thanks!

**Comment by amandafrench** [comment]
Just a note that I'm going to keep this issue open until we plan the next sprint and will include it there so we remember to test it at the end of August.
