### ISSUE TITLE
Investigate whether Altmetrics badges can run from BOTH the handle and a DOI

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#322]
We implemented a feature called the "Altmetrics badge" a few months ago, thanks to @AmberPoo1's good work. See #181 and #199 and #207 especially. The badge we currently have is tracking the number of times people have shared the item record handle, so, for instance, when someone tweets the link http://hdl.handle.net/10919/64842 (or, I think, http://vtechworks.lib.vt.edu/handle/10919/64842), the Altmetrics badge shows 1 tweet. (It doesn't work for the individual file links.) 

The altmetrics badge can also track when someone shares a Digital Object Identifier such as http://dx.doi.org/10.17613/M6NW2R, but their documentation suggests that it's an either/or proposition. I'd like to see if we can either 1) configure the current badge so that it will ALSO track DOIs, or 2) add an additional altmetrics badge to the system that will display a second badge for DOIs. 

Documentation here: https://api.altmetric.com/embeds.html -- altmetrics staff can also answer questions.

**Comment by AmberPoo1** [comment]
Using two badges together for handles and DOIs is one way, another possible solution is to use raw Altmetric API. Introduction can be found here: http://api.altmetric.com/, https://help.altmetric.com/support/solutions/articles/6000092312-how-can-i-access-the-altmetric-api-documentation-. 
Complex query and customization can be done with Altmetric API, however, commercial license is required to use "Fetching detailed information about an article or dataset" API, which seems like what we want. Please refer to this page: http://api.altmetric.com/docs/call_fetch.html for the details.

**Comment by amandafrench** [comment]
@AmberPoo1 Thanks! We did actually just subscribe to the Altmetrics Enterprise package, so we might be able to get this.

**Comment by alawvt** [comment]
@amandafrench, would you get us any authorization credentials and informaiton for this?

**Comment by amandafrench** [comment]
I've left Julie a message and will email her as well to get our API key. According to the page at https://www.altmetric.com/products/altmetric-api/ , the "Commercial API" is included with "Explorer for Institutions" (which apparently we have purchased).

**Comment by amandafrench** [comment]
I'm going to close this, since we're waiting on the API key from Julie.

**Comment by alawvt** [comment]
When a user mentions the publisher's article URL, we pick up a DOI in the page metadata, but not a Handle. That is because the publisher does not use your Handle in their metadata.
 
When a user mentions your IR's article/output URL, we pick up both a Handle as well as a publisher DOI, as you've included both in your metadata. This is great, but it's useful to keep in mind that we only ever see your Handle when someone actually mentions the IR page.
 
This means that if the IR article/output page is never mentioned online, then Altmetric will not have any record of the Handle - therefore your badge will not appear as it is specifically using the Handle. If the publisher article URL is the only version that gets mentioned, then that means Altmetric will not make any connection between the Handle and the DOI until the IR page is also mentioned later. (If the IR version is the only that gets mentioned, then Altmetric will be able to see the Handle and the DOI, so the record will still be associated with the DOI.) 

In order for Altmetric to build a record that includes both a Handle and a DOI, we would have to see the two identifiers together somehow, in the same place - whether it's on your IR page or somewhere like Crossref. Handles are not included in Crossref (where Altmetric retrieves a lot of metadata to build records), so at the moment, unless the IR page is mentioned, there is no way for Altmetric to "know" of the Handle. 
 
The Altmetric APIs won't help you either in this instance because unless the IR page with the Handle has been mentioned, we won't have the Handle stored in the record along with the DOI.
 
I would suggest that if using the DOI only is a problem, you could implement two badges - there will likely be more elegant ways of showing this, but one example of another IR with a similar problem (with URNs, not Handles) has done this:
 
http://liu.diva-portal.org/smash/record.jsf?pid=diva2%3A1199053&dswid=-2082
  
Jean Liu  
Head of Product, Altmetric  
www.altmetric.com

**Comment by alawvt** [comment]
DiVA, http://liu.diva-portal.org, from Linkoping University utilizes multiple Altmetric badges for different sources: one for doi, one for isbn, and one for urn-nbn.

No badge is displayed if the Altmetric score for that source is 0. Also, the isbn badge is often hidden, but it does display in the mouse over, if it has a value.

http://liu.diva-portal.org/smash/record.jsf?pid=diva2:1199053 has one Altmetric badge for doi and another for urn-nbn. They both link to the same Altmetric record. According to Jean Liu’s explanation, we would expect this if Altmetric has associated the urn with the doi. If they haven’t been associated, we would expect different links, which we could test.

http://liu.diva-portal.org/smash/record.jsf?pid=diva2:892958 has only an Altmetric badge for the doi.

http://www.diva-portal.org/smash/record.jsf?pid=diva2:1146061 has an Altmetric badge only for the urn-nbn.

http://liu.diva-portal.org/smash/record.jsf?pid=diva2:1204256 has one badge for doi and another for urn-nbn but hovering over it shows three badges: with another for ISBN. These all link to the same Altmetric record.

http://liu.diva-portal.org/smash/record.jsf?pid=diva2:1104409 has one badge for isbn.

Code from http://liu.diva-portal.org/smash/record.jsf?pid=diva2:1204256
```
<div id="formSmash:altmetricDiv" class="altmetricDiv">
<div class="altmetric-embed doi" 
data-badge-type="donut" 
data-link-target="_blank" 
data-hide-no-mentions="true" 
data-doi="10.3384/lic.diva-147719" 
data-uuid="5664cbbe-422e-2d91-76c7-5f5f39af8f1f">
</div>
<span class="altmetric-label">doi</span>
<div class="altmetric-embed isbn" 
data-badge-type="donut" 
data-link-target="_blank" 
data-hide-no-mentions="true" 
data-isbn="9789176853016" 
data-uuid="cb6bf936-e622-2eda-c88e-d31ae05d64a0">
</div>
<span class="altmetric-label">isbn</span>
<div class="altmetric-embed urn-nbn" 
data-badge-type="donut" 
data-link-target="_blank" 
data-hide-no-mentions="true" 
data-urn="urn:nbn:se:liu:diva-147719" 
data-uuid="57c8c3ae-bffc-66a3-7bb6-e6e4ad2ab882">
</div>
<span class="altmetric-label">urn-nbn</span>
</div>
```
