### ISSUE TITLE
Update Policies page from Drive

### ISSUE THREAD

**Issue by pgray64** [VTUL/vtechworks#362]
Update the text of the Policies page from the most recent changes in the VTW Google Drive

**Comment by pgray64** [comment]
Pull request #367

**Comment by mello99** [comment]
Hi @amandafrench , there are a few suggestions that need to be approved in the updated [Policies document](https://docs.google.com/document/d/1kkSKHIVM3q46TIDzCmQm90dS5UNyXKMDIuTd_mDWSSg/edit#) since they were added in "Suggesting" mode. Once you've approved (or rejected) these suggestions, could you please let me know? @pgray64 , as soon as Amanda approves the unapproved suggestions in the Policies page, the new policies page is ready to go on Drive.

**Comment by amandafrench** [comment]
I reviewed and accepted these, although too late for them to go live in the current deployment. @pgray64, please do see the current version in Google Drive as of 8/30 and encode them for the Policies page. Thanks.

**Comment by AnushaPillai** [comment]
resolved with pull request #401
