### ISSUE TITLE
Unable to upload wireframe videos (Fix ClamAV settings)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#390]
Hi all, Andi contacted me a few days ago and explained that she was unable to load several wireframe videos to an item she was creating in VTechWorks. I wrongly assumed that I had the magic touch and could upload the wireframe videos myself; after the first upload reached 100%, I received the following message:

![screen shot 2016-09-13 at 12 39 48 pm](https://cloud.githubusercontent.com/assets/5408616/18482779/8fbd9520-79af-11e6-9c1f-2f72c7a9d9ae.png)

It's not a size issue - none of the wireframe videos are over 220 MB. Does anyone know what's causing this? Please contact me if you'd like access to the wireframe videos, and thanks so much.

**Comment by alawvt** [comment]
@mello99, thank you for reporting this issue. Would you upload one of these files to the Google Drive/VTechWorks Team/Technology/ folder for us to use for testing?  

Also, would you mind creating a test item on dev with just a pdf as the submitted file, then see if you can add the wireframes in the "edit this item" view? If this works, you could create the item this way on production, then delete the unneeded PDF, then load the wireframes manually.  

@pgray64, please look into this issue and see if ClamAV has any restrictions for file formats, etc. that might be causing this problem.

**Comment by alawvt** [comment]
I just tried the curation task, "Scan for viruses," on http://vtechworks.lib.vt.edu/handle/10919/72937, which contains one PDF file. It returned

```
Task: Scan for Viruses
The task was completed successfully.
STATUS: Success, RESULT: Item: 10919/72937 had no viruses detected.
```

I then tried the curation task, "Scan for viruses," on http://vtechworks.lib.vt.edu/handle/10919/18665, which contains Project_arunima2_nik90.zip (451.6Mb) and UpwardBoundTalentSearch.mp4 (73.43Mb). It returned 

```
Task: Scan for Viruses
The task was completed successfully.
STATUS: Error, RESULT: Error encountered using virus service - check setup
```

I think this is because it exceeds the Max File Size and Max Scan Size: 100M setting for ClamAV.

I then tried the curation task, "Scan for viruses," on http://vtechworks.lib.vt.edu/handle/10919/47524, which contains  HayesDonald_transcript.pdf (61.95Kb) and HayesDonald_interview.wmv (51.13Mb). It returned

```
Task: Scan for Viruses
The task was completed successfully.
STATUS: Success, RESULT: Item: 10919/47524 had no viruses detected.
```

So it seems like it is the file size setting and not the file type that is causing the error.

https://github.com/VTUL/vtechworks/issues/91 lists the current file submission limit of ~2 GB, due to the Cocoon issue.

https://github.com/VTUL/vtechworks/pull/314 lists the current ClamAV settings. I'm working on testing higher limits.

**Comment by mello99** [comment]
Thanks for clarifying this, @alaw. Let me know if you need help with the additional tests.

**Comment by mello99** [comment]
I successfully uploaded the wireframe MOV files using the "Edit item" functionality (which can be accessed after an item is created in VTW). The item can be accessed [here](http://hdl.handle.net/10919/72942). Thanks.

**Comment by alawvt** [comment]
@mello99, thank you very much for testing the alternate upload method and loading this item manually.

I created a GitLab wiki page with notes about [ClamAV in VTechWorks](https://git.it.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/ClamAV).

**Comment by pgray64** [comment]
Even with

```
MaxScanSize 4000M
MaxFileSize 4000M
StreamMaxLength 4000M
MaxRecursion 100
```

and multiplying all timeouts by 10

Uploading a 217 mb MP4 fails, as does a 1 Gb mov.

**Comment by pgray64** [comment]
ClamAV's Clamscan is able to scan the 1Gb mov with `--max-scansize=2000M --max-filesize=2000M` arguments. Perhaps DSpace has a timeout for calling the external ClamAV daemon.

**Comment by pgray64** [comment]
Large files were failing due to a too low `socket.timeout` in [dspace]/dspace/config/modules.clamav.cfg. I changed it to `socket.timeout=120000` (120 seconds).

When testing MOVs and MP4s, some video files needed ClamAV settings `MaxScanSize, MaxFileSize, StreamMaxLength` to be 20X that of the uploaded file size for the scan to not fail.

**Comment by alawvt** [comment]
@pgray64, thank you very much for your extensive testing and resolution of this issue.

Depending on the file format, files up to 2 GB (possibly much smaller) may be loaded via the submission form. Larger ones will have to be loaded in the "edit this item" interface or on the command line.
