### ISSUE TITLE
When dc.identifier.orcid contains an ORCID, make it a hyperlink to the ORCID profile

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#403]
@amandafrench, the dc.identifier.orcid field does not appear in the Simple Item View, only the Full Item view. In the Full Item View, none of the URLs, e.g. http://vtechworks.lib.vt.edu/handle/10919/27948?show=full, are live links unless someone has entered them in a <a href> tag, e.g. http://vtechworks.lib.vt.edu/handle/10919/64842?show=full. Are you asking that the DOI be a live link in the full record view by default?

**Comment by amandafrench** [comment]
@alawvt I'm asking that in Full Item View both the ORCID and the DOI be automatically wrapped in `<a href=""></a>` tags so that they become live links automatically. As @keithgee has said, this is the way the URI field works, so it shouldn't be too hard to do it for these fields. You just grab the text string in the field and stick it in the tag like `<a href="http://doi.org/10.blahblahblah">` and it becomes a live link.

**Comment by alawvt** [comment]
Please create the ORCID as a link in the submission form, for example

```
<a href='http://orcid.org/5412-3652-8965-8745'>5412-3652-8965-8745</a>
```

**Comment by alawvt** [comment]
Continued in #764.
