### ISSUE TITLE
Off Campus LogIn (EZproxy) requires multiple clicks to view restricted file.

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#408]
@mello99 noted, "I can access restricted file, but not in the most straightforward way. In short, when I first sign-in with ez-proxy, then go to the following URL,"https://vtechworks.pprd.lib.vt.edu/handle/10919/53800", I can't access the item. Then when I click on "Off-campus sign-in" again, I can access it, "https://vtechworks-pprd-lib-vt-edu.ezproxy.lib.vt.edu/handle/10919/53800". Quirky, but it works eventually."

I experienced the same thing, needing a couple page refreshes after logging with EZproxy for the "OffCampus Sign In" logo to change to "Logged in." Perhaps DSpace is not getting the information that the IP address has changed or it needs to check the group rights again. Since RS has pointed out that our implementation of OffCampus is outdated, we might want to take on this issue on a larger scale.

**Comment by keithgee** [comment]
I have a hunch that what @mello99 mentioned, at least, might be normal EZProxy behavior. When we directly access https://vtechworks.pprd.lib.vt.edu/handle/10919/53800, which is probably what I put in the test plan, we're not going through EZProxy.

Clicking that off-campus sign-in button will then cause the page to be reloaded, but through EZProxy, and the links on the page, including the links to the bitstreams, will then also go through the EZProxy server because they start like this "https://vtechworks-pprd-lib-vt-edu.ezproxy.lib.vt.edu/".

@alawvt are you still experiencing the issue where you need to refresh the page?

**Comment by alawvt** [comment]
@keithgee, I tested this on production from off campus. I can't see the URLs using a http://free-proxyserver.com, so it would be hard to trace now. I could test it again from home next week and report what URLs I see.

**Comment by alawvt** [comment]
@mello99, if you had time this week, it would be very helpful if could test this further. Please record the detail of each step of trying to use EZproxy, including the URL of each link that you click on or page that you refresh. EZproxy works by rewriting the URLs, so that is key to trace what is (or isn't) happening. Thanks.
