### ISSUE TITLE
Add takedown language to footer

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#443]
Please start with a placeholder for a statement like the one in the footer of https://www.repository.cam.ac.uk/.

**Comment by pgray64** [comment]
I've added the takedown notice to the footer in new branch:
https://github.com/VTUL/vtechworks/tree/footer-takedown-message

Didn't make a pull request since the link doesn't link to anything currently.

![screen shot 2016-11-30 at 1 57 06 pm](https://cloud.githubusercontent.com/assets/7339589/20766567/ea6ca140-b704-11e6-9243-5d920fdaad8a.png)

**Comment by amandafrench** [comment]
Thanks, @pgray64 and @alawvt! I finished this section last night -- it's live on the Google Site and can be linked to at https://sites.google.com/a/vt.edu/vtechworks-help/policies#TOC-Requesting-that-Material-be-Amended-or-Removed Please change the language in the footer to read as follows: 

***

If you believe that any material in VTechWorks should be removed, please see our policy and procedure for [Requesting that Material be Amended or Removed](https://sites.google.com/a/vt.edu/vtechworks-help/policies#TOC-Requesting-that-Material-be-Amended-or-Removed). All takedown requests will be promptly acknowledged and investigated.

**Comment by pgray64** [comment]
Updated the footer. Pull Request #445
