### ISSUE TITLE
Review latest RSS configuration on vtechworks.dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#450]
Continues Issue #384 and PR #447.

@amandafrench, I am bewildered why this looks so different than it did when I tested your PR. Unfortunately, yesterday when I was having difficulty with my LDE, I just made that change to webui.feed.item.dc.creator without testing it. Would you look at the current configuration on vtechworks.dev and see if this is the intended change?

For view-source:https://vtechworks.dev.lib.vt.edu/feed/rss_2.0/10919/5534 in Chrome,
```
<item>
<title>Vector Instruction Set Extensions for Efficient and Reliable Computation of Keccak</title>
<link>http://hdl.handle.net/10919/72857</link>
<description>Rawat, Hemendra Kumar
</description>
<pubDate>Sat, 27 Aug 2016 00:00:00 GMT</pubDate>
<guid isPermaLink="false">http://hdl.handle.net/10919/72857</guid>
<dc:date>2016-08-27T00:00:00Z</dc:date>
<dc:description>Recent processor architectures...overhead of just 6%.</dc:description>
</item>
```
It is strange having both a `<description>` element (for author) and a `<dc.description>` element for the abstract. In the Vienna RSS viewer for this page, only the `<description>` appears. In Firefox, only the `<dc:description>` appears.

**Comment by amandafrench** [comment]
@alawvt The source code you post above looks exactly as it did when I made the change on my LDE, so to me the above passes testing. As I mentioned in the comment for PR #447, this change puts the author in the ```<description>``` element for all syndication feeds. Yes, it is strange to have the author in the ```<description>``` field and then the abstract in ```<dc:description>```, but that's a hack I had to do in order to get the author to show up at all in a separate field.  

I don't know why you didn't see the authors in the ```<description>``` field in the source code you posted in PR #447, though, since that's specifically what this change is supposed to do. There might be caching issues; cache values are also specified in the Syndication settings in dspace.cfg.

**Comment by amandafrench** [comment]
@alawvt Let's only look at the source code of syndication feeds, by the way, which should be the same in all browsers and aggregators and viewers; all the clients will display that code differently on the front end, but we can't do anything about that.

**Comment by alawvt** [comment]
@amandafrench, thank you for reviewing this. I am glad that it meets your specification. We will move testing to pprd now.
