### ISSUE TITLE
2 ETDs didn't process with ETD script; uploaded them to be processed again tomorrow

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#48]
The Grad School ETD script threw error messages (not XML or zip problems) for 2 of 3 ETDs it processed this morning. I tested batch uploading and the database seems ok. I reloaded the 2 ETDs to the FTP server and we'll see if they are processed tonight.

**Comment by keithgee** [comment]
@alawvt if there are similar problems on the next run, you might want to open a TeamDynamix ticket so that ITS can look into it.  The scripts were able to load items into VTechWorks fine prior to today (for the few days they after they had been re-enabled.) It's my understanding, based on other issues you have been dealing with today, that there was some difficulty running the /dspace/bin/dspace command. 

This command  is used by the scripts, which are scheduled in the cron table for the vtechworks user, to ingest content. It's possible that something user/group/permission related has changed on the server in the last day. If there are continuing similar issues, Aaron and Francis might be best at solving and getting them working again.

**Comment by alawvt** [comment]
@keithgee, thank for your ideas on this issue. I'm glad you pointed out the possible connection between the permission issue and this one. I will report it on TeamDynamix if it doesn't resolve or if it reoccurs.

**Comment by keithgee** [comment]
@alawvt I hate to undo recent work, but I'm wondering if we should disable the cron job until it's resolved. You've had to re-upload things to the FTP server, and also, is one of the scripts emailing out the strange error messages to our users?

Also I wanted to clarify that I'm happy to help if any work is needed from me; I do just feel that ITS may have a better handle on how to fix the issue and also should be aware so that it's less likely to happen again.

**Comment by alawvt** [comment]
@keithgee , thank you very much for your assistance. Both scripts ran correctly through Thursday morning. They failed Friday, Saturday, and Sunday. I will submit a TeamDynamix request.
