### ISSUE TITLE
Images in 4/16 collection description not appearing

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#487]
The [4/16 Condolence Archive collection](https://vtechworks.lib.vt.edu/handle/10919/11385) has numerous images in the collection description and they are not being displayed. In Firefox they are completely absent. In Chrome, shown below, ![4_16_collection](https://cloud.githubusercontent.com/assets/13037168/24610691/908eb852-184d-11e7-8ed9-acbe47a781dc.jpg) the broken image symbols are displayed. These images did work last year because I created the ViewShare image on 2016-04-16.

**Comment by keithgee** [comment]
Last September/October some security settings were hardened by ITS for VTechWorks, including the addition of a Content Security Policy. We didn't think to review this customized page in our test plan. Here's the related task in GitHub.

https://github.com/VTUL/vtechworks/issues/388

The current Content-Security-Policy header suggests that browsers disallow images loaded via 'http'. They must be loaded via 'https'. 

```
img-src https: ;
```

I've logged into DSpace with DSpace administrator privileges and edited the description for this collection so that previous "http" links are now "https" links to the same resources. The images are now displaying.

Side note related to images in this collection: Many items in this collection have bitstreams in the BRANDED_PREVIEW bundle. They are versions of the original image, sized larger than a thumbnail but smaller than the original, intended to be displayed inline in the browser on the item view pages. The current VTechWorks theme doesn't support this, but it's a small theme change to enable this feature once again for the 4/16 collection. It would require a deployment.

***Closing

**Comment by alawvt** [comment]
@kdweeks, thank you very much for reporting this issue.  
@keithgee, thank you very much for fixing this.

**Comment by alawvt** [comment]
@keithgee, I did a search for "http://" and found 13 items with this possible problem. I will check them - done.
