### ISSUE TITLE
Install DSpace 6 on your LDE and document the procedure

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#490]
Please install DSpace 6 on your LDE and document the procedure in the vtlibans wiki page, [DSpace 6 Installation](https://git.it.vt.edu/it-services/vtlibans_dspace/wikis/dspace_6). I think it makes sense to add it a a branch to this repository, using the instructions in https://github.com/VTUL/vtechworks/wiki/Upgrading-VTechWorks-for-DSpace-point-releases. @keithgee, do you have any thoughts on this? You can also create a new branch on the vtlibans project for any changes, if desired. 

We won't need to install the scripts for Elements in DSpace 6.

It will be a while before we can install DSpace 6 for the repository, but we would like to know what is involved for the installation and  be able to use it on our LDEs for some of the database querying functionality that is available with DSpace 6.

**Comment by keithgee** [comment]
@alawvt, I think the quickest way to get a version of DSpace 6 with our data in it for the purposes of database querying and general testing may be to start with a pre-existing VTechWorks LDE running DSpace 5.x, and then follow the upgrade instructions on the documentation wiki:
https://wiki.duraspace.org/display/DSDOC6x/Upgrading+DSpace

If and when we commit to upgrading to DSpace 6 for the dev/pre-prod/production machines, we'll need to strategize about how to accomplish that. Here's a first rough idea:

- Get the latest code from the main DSpace project
- Create a vt_6_x_dev branch in VTUL/VTechWorks with the latest DSpace 6 release as a base
- Customize default configuration files with values appropriate for our setup and commit to vt_6_x_dev (or ansible project as appropriate)
- Look through our history to figure out which customizations we need to migrate to DSpace 6. If we're fortunate, most will be in modules and our custom theme
- Copy and commit required modules and themes to the vt_6_x_branch
- Build and test according to the test plan
- Fix and verify
- Adjust Ansible project as needed
- Deploy
- Make vt_6_x_dev the default branch in our repository

This is a little bit different from the point release upgrades, because in this case we would start with the canonical DSpace release as a base and then customize with our needed changes. When we do point upgrades we usually just merge the fixes into our already customized branch. There are a lot of ways to do this; maybe you and @pgray64 also have ideas.

**Comment by alawvt** [comment]
@keithgee, thank you very much for these ideas. 

@pgray64, please try the upgrade path that @keithgee linked first with a new LDE and record the experience (steps needed, time and effort required, problems). 

Then let's begin the path that @keithgee has outlined by creating a vt_6_x_dev branch and trying to get that to work with  default DSpace.

**Comment by ankur-a** [comment]
Can anyone help in integrating video playback feature on dspace 6? I'm facing an error on playing videos on chrome and other browsers except firefox which seems to smoothly play the video. 
Chrome is showing 
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.
in its console

**Comment by keithgee** [comment]
@ankurcode, we haven't tried this with DSpace 6 yet. We're waiting to upgrade because of dependencies with another system that is integrated with our repository.

I might be able to peek at your issue in about two weeks - please ping me then to remind me.
Thanks!

**Comment by ankur-a** [comment]
We have succesfully installed dspace 6 on ubuntu sever 16.04 and steps can be found in.
 https://github.com/fresearchgroup/oer/wiki/DSpace-installation-procedure
