### ISSUE TITLE
Integration of video streaming in Dspace 6

### ISSUE THREAD

**Issue by ankur-a** [VTUL/vtechworks#499]
Can anyone help in integrating video playback feature on dspace 6? I'm facing an error on playing videos on chrome and other browsers except firefox which seems to smoothly play the video.
Chrome is showing
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.
in its console

**Comment by keithgee** [comment]
@ankurcode I may be able to help in about two weeks. We're on DSpace 5 now. I haven't tried to add our video playback code to DSpace 6, so I'm not aware of the particular issues.

Video playback isn't included with DSpace, you have to add it on.

If you're using HTML 5 playback, as we're doing with VTechWorks, the videos have to be in formats that your browser understands.
You might look for a chart that shows which browser understands which formats. There's an example on this page, though it may not be up to date:

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

For our implementation, which now about five years old, we chose to encode each video in two formats: mp4 with h.264 video and AAC audio, and webm with VP8 video and Vorbis audio.  We also had to encode in a particular colorspace, because we found that Chrome didn't understand some color spaces.

Our implementation is out of date now - for example, most browsers understand h264 so our additional webm files may not be helpful anymore. Also, our videos are currently encoded in relatively low resolution, while HD video (1920x1080) is quite common in the United States now. Browsers are also starting to add support for h.265/HEVC and it could be widespread within 5 years.

I may be able to help more in about two weeks if you're still stuck. Please get in touch with me in about two weeks if that's the case.

In the meantime, could you advocate for some sort of video streaming feature to be added to DSpace 7? It's listed as a potential feature on the DSpace 7 release status page - maybe you could chime in and say it is desired in your repository:

https://wiki.duraspace.org/display/DSPACE/DSpace+Release+7.0+Status

**Comment by keithgee** [comment]
I forgot to mention that if you have a budget to add a video streaming feature to the repository, I recommend having a chat with @bram-atmire. The atmire company has done some work for clients before related to video playback in DSpace.

**Comment by ankur-a** [comment]
Thanks to your paper on the integration of video and also pdf streaming I was able to integrate the same feature on Dspace 6 with minor changes.
