### ISSUE TITLE
Error loading PDF of http://hdl.handle.net/10919/56312

### ISSUE THREAD

**Issue by cecross1** [VTUL/vtechworks#500]
A user tried to download the PDF for [http://hdl.handle.net/10919/56312](http://hdl.handle.net/10919/56312), and he stated that the file would not load, even though it's not restricted. I tested the link using a VPN site, and received the error message "Failed to load PDF document". It's a large file, so maybe that's the reason for the error? I resolved the issue by emailing the PDF directly to the user, but thought someone should know in case other items are affected.

**Comment by keithgee** [comment]
Thanks @cecross1. 
It seems to be working now such that I can't duplicate the problem anymore, from the office or from a mobile phone on an external network. For a brief window today after you reported this problem, I also received an error when I tried to load PDF files on VTechWorks, but only with Safari 10.1.2 on macOS. 

I will tag @zoto724 to let him know that the error, in my case, was about the Content-Security-Policy header - Plugin blocked: uri [of the PDF] not specified in object-src directive. The CSP header didn't look odd to me or like it had changed, so perhaps my browser was just having an unrelated glitch. I'm able to load PDFs fine in VTechWorks again without any configuration changes.
 
I'll close this because you've helped the user and I can't duplicate the issue, but you can reopen it if you can still duplicate the issue or if it occurs again.

Thanks!

**Comment by keithgee** [comment]
Additional note: I can recreate the blocked plugin error on Safari 10.1.2 on macOS when I am signed into my Gmail account. When I'm not signed in, everything works as expected. 

When I am signed into Gmail, this browser tries to POST data to https://mail.google.com/mail/cspreport, which seems to cause the problem. I don't see a report-uri directive in the CSP. Perhaps it's a browser bug.

**Comment by keithgee** [comment]
Can now load the PDF fine when signed into Gmail. (And it's no longer trying to post a CSP report). Confused and giving it a rest for the evening.

**Comment by cecross1** [comment]
Thanks, Keith!  When I got the error, I had tried loading the PDF in both Chrome and Firefox. I was also signed into Gmail at the time, so I wonder if that had something to do with it? If it happens again, I'll reopen the ticket.
