### ISSUE TITLE
Thumbnail not showing up in submission

### ISSUE THREAD

**Issue by cecross1** [VTUL/vtechworks#517]
I uploaded a batch of newsletters to the Reports, news, etc., Department of Mining and Minerals Engineering Collection, but for some reason, one item doesn't have a thumbnail, even though it's been a couple of days. The item can be found here: http://hdl.handle.net/10919/81509. Thanks!

**Comment by keithgee** [comment]
@cecross1, the ImageMagick Thumbnail filter that we have configured to create thumbnails sometimes fails.

There's an older, alternative thumbnail filter that doesn't use ImageMagick that we could try, but the quality of that filter tends to be lower.

For now, since there is only one item with this issue, instead of configuring the old filter or debugging the issue with the new one, I've manually created a thumbnail. I saved the PDF to my computer, opened it with preview, took a screenshot, resized the image so that it was not larger than 80 pixels in width or height, then converted it from .png to .jpg. This seemed a bit clumsy, so if this happens again you can use whatever method you want to get a thumbnail not larger than 80 pixels wide or high. (Side question: This our standard thumbnail size, but doesn't it seem too small to be useful?)

I named the new thumbnail image with the same filename as the PDF, but with an appended ".jpg" at the end of the filename. Then I logged into VTechWorks, edited the item, went into the bitstreams tab, and added this file as a new bitstream, making sure to put it into the "Thumbnails" bundle.

Thanks for reporting this. The thumbnail is displaying on the page now. Let me know if you have any questions.

*** Closing

**Comment by cecross1** [comment]
@keithgee 
Thanks for taking care of this. I agree that the standard thumbnail size is
small, but if it's an image with a lot of detail, I wonder how big it would
need to be to actually be legible.
