### ISSUE TITLE
In patent collection, item dc.type  is not indexed 

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#518]
Patents in the [Virginia Tech Patents collection](https://vtechworks.lib.vt.edu/handle/10919/72294) all have `dc.item.type`="Patent." However this value is not indexed in content type, ["Patent"](https://vtechworks.lib.vt.edu/discover?field=type&filtertype=type&filter_relational_operator=equals&filter=Patent). I tried to force re-indexing by moving the value from `dc.type[]` to `dc.type` but this had no effect.

**Comment by keithgee** [comment]
In our [vtechworks/dspace/config/spring/api/discovery.xml file](https://github.com/VTUL/vtechworks/blob/2cc0dbf6f854eb146d78d521f296e0844a473be5/dspace/config/spring/api/discovery.xml), the DSpace Discovery interface has been customized for the patents collection. In this configuration, dc.type has been omitted. I think this was done because all of the items in that collection are of type "Patent", so it didn't make sense to filter that collection by type.

This is a hunch, but perhaps this is what is causing dc.type to not be indexed. Perhaps the configuration changes the indexing of all items in the collection, even when viewed from outside the collection.

Some support for this hunch:
- ETDs also have a custom configuration, but "type" is still indexed in that configuration. ETDs are indexed by type.
- If you change the type of an item in any other collection to "Patent", that item will appear in the "Content Type" sidebar of VTechWorks as a Patent. It looks like the patents collection is the only place where this isn't happening.
- Solr appears to be re-indexing items without issues lately

A way to prove/disprove this hunch could be to add the type field into the discovery configuration for patents (search? sidebar? somewhere else?) on a test system, do a complete rebuild of the solr index, and then look to see if the problem is solved.

**Comment by keithgee** [comment]
One more nugget of support for the hunch:

- If you pick an item in the patent collection and move it to any other collection, it will then be visible in the "type" index as a "Patent". If you then move that item back into the patent collection, it will vanish from the "type" index again.

**Comment by keithgee** [comment]
Also, it seems that dc.type is being indexed in at least some way for the patents under the current configuration. If you go into the search bar of VTechWorks and type in "dc.type:Patent" (but without quotation marks) all of the patents appear.

**Comment by alawvt** [comment]
@keithgee, thank you very much for investigating this issue. I will add a task to the backlog to experiment with the facet configuration and, if necessary, to report this issue to the DSpace project.
