### ISSUE TITLE
Submission fails at Creative Commons licence step due to new CC API URL

### ISSUE THREAD

**Issue by cecross1** [VTUL/vtechworks#520]
When I attempted to upload the attached conference paper to the collection: [DA: Integrated Security](https://vtechworks.lib.vt.edu/handle/10919/79979), I got the generic error message screen (please see attached screen shot). I tried submitting twice, first with the dc.type: presentation, and the second time with the dc.type: other, but neither attempt was successful. 

Today, I successfully uploaded a couple of articles to the same community without any issues, so maybe it's a problem with the submission type? Could someone please take a look at this? 

[VTW submission error 4.2.18.pdf](https://github.com/VTUL/vtechworks/files/1869010/VTW.submission.error.4.2.18.pdf)
[DeYoungPrivacy2018.pdf](https://github.com/VTUL/vtechworks/files/1869015/DeYoungPrivacy2018.pdf)

**Comment by keithgee** [comment]
File is about 1 megabyte.
There is plenty of disk space available.

We have tried all of these things:

 - Resuming the previous submission
 - starting from the beginning
 - changing the dc.type field
 - useing two different accounts (Carrie's and Keith's)
 - submitting on pre-prod
 - submitting with a different file

I can't find error messages in the logs related to this problem.

**Comment by keithgee** [comment]
We've also tried submitting to a different collection in pre-prod.

The submission always fails just before the CC license. I will try to disable Creative Commons step in pre-prod, test other submissions with both Article type and Presentation type, and then either update the ticket or speak with Carrie about the results.

**Comment by keithgee** [comment]
@cecross1, I was able to upload to pre-prod after disabling the Creative Commons step. I uploaded one item with Article type (to Chem collection, I think) and another article with Presentation type to the "DA: Integrated Security" collection.

Tomorrow, if you're able to upload to pre-prod, and still not able to upload to production, a next step might be for me to prepare a fix to /dspace/conf/submission.xml (where the CC license step can be disabled) and then ask @zoto724 to schedule a deployment with his staff.

I've put a notice on VTechWorks production:
`One user experienced problems submitting new items to VTechWorks on Monday, April 2, 2018. Please contact vtechworks@vt.edu if you experience problems so that we may assist in adding your item`

I'll also send a note to the dspace-tech mailing list to see if others are experience CC license issues or have other suggestions about how to handle it.

**Comment by keithgee** [comment]
On the dspace-tech list, there are reports from three other institutions that are experiencing problems with CC licenses today.

**Comment by keithgee** [comment]
The Creative Commons API moved to a different server yesterday. It was down for a while, and when it came back up it still didn't work with DSpace systems. On the dspace-tech list, some, but not all libraries were able to resolve the problem by changing the cc.api.rooturl configuration to use https instead of http.

https://groups.google.com/forum/#!topic/dspace-tech/FCEX2tWbq7g

It seems like the Creative Commons team is working out some other problems with the API as I type this, though.  One possibility is to disable the Creative Commons license step on production temporarily, and then when the CC API service is stable again, enable it with the https url. I'll be out tomorrow through Friday; @alawvt may be back tomorrow or Thursday.

**Comment by cecross1** [comment]
Thanks, @keithgee. I submitted a test item to the [Library Test collection](https://vtechworks.pprd.lib.vt.edu/handle/10919/64337) on preprod, and it seems to have gone through. I also tried to resend my saved submission from yesterday on the main site, but it still didn't go through. 

Let me know if you find a workaround. We're expecting many new item submissions to the [Undergraduate Research community](https://vtechworks.lib.vt.edu/handle/10919/10194) around this time.

**Comment by keithgee** [comment]
@cecross1, do the Ungraduate Research Community submissions need Creative Commons licenses? If not, my suggestion for now is to disable the Creative Commons step to give the CC team some time to stabilize everything.

We can enable it again later using the https protocol instead of http.

**Comment by cecross1** [comment]
@keithgee, I think it's optional (some students choose to have one, but many don't). So if you or @zoto724 could disable this step, that would be helpful.

**Comment by cecross1** [comment]
Update: I just received several reports from students who can't get past the CC license step to submit to 
[CS4624: Multimedia, Hypertext, and Information Access](https://vtechworks.lib.vt.edu/handle/10919/18655).

**Comment by keithgee** [comment]
Carrie, I just made a temporary patch for the problem, and submitted a 4Help request. I'll also email library ITS to ask for assistance in disabling CC license..

**Comment by keithgee** [comment]
Leaving a link to the necessary change for ITS staff:
https://github.com/VTUL/vtechworks/commit/88da035bb78ca77c16062b82f7613057b6d91b7a

**Comment by keithgee** [comment]
Aaron has made the change and Carrie tested and verified that submissions are functioning. I'll leave this issue open to remind us to enable CC Licenses again (perhaps with the https option) when the CC API servers are stable again.

**Comment by alawvt** [comment]
The contact from Creative Commons announced on that thread on the DSpace Tech listserv, 
>We should move the API to https-only at some point in the future to help keep user information private, but it shouldn't happen without warning.

I have reverted the patch with 22681a8104 in branch vt_5_x_prod_deploy to re-enable the Creative Commons step in the submission form and notified IT Services.

**Comment by keithgee** [comment]
This makes me wonder if we just should have waited ( we only got a few submissions), but it was hard to predict when it would be working again.

Edit: waited as in "not deployed an emergency fix and waited for CC team to fix the issues"

**Comment by alawvt** [comment]
@keithgee, I think you made the right choice because we had no information about when and how it would be resolved by CC. Thank you very much for handling this. 

@cecross1, thank you very much for reporting this issue and testing.

The reversion has been applied and the CC step now works again.

**Comment by keithgee** [comment]
Hi, just noting that there's a message on the DSpace-tech mailing list that hints this problem may have returned. I haven't noticed anything with VTechWorks, but it might be worth checking into tomorrow and then closing this if everything is okay.

**Comment by keithgee** [comment]
Closing.
Not seeing issues with uploading items today.

**Comment by alawvt** [comment]
This didn't get reverted in the vt_5_x_dev branch, only the vt_5_x_prod_deploy branch. I will revert it in vt_5_x_dev.

**Comment by alawvt** [comment]
This reversion has been deployed and tested on vtechworks-dev.

**Comment by alawvt** [comment]
It has been deployed to vtechworks-pprd and vtechworks production. All tests have passed. Thank you very much, @soumikgh, for all your assistance.
