### ISSUE TITLE
Items from initial Computer Science Technical Reports migration each have two dc.date.accessioned and dc.date.available

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#548]
In wading through the Elements RT2 logs, it seems that in the initial migration of the Computer Science Technical Reports database to VTechWorks, all 994 items have two values for dc.date.accessioned and dc.date.available. An example of this is http://hdl.handle.net/10919/20079

dc.date.accessioned | 2013-05-28T20:43:14Z | en_US
-- | -- | --
dc.date.accessioned | 2013-06-19T14:37:05Z |  
dc.date.available | 2013-05-28T20:43:14Z | en_US
dc.date.available | 2013-06-19T14:37:05Z |  

Most of the other fields in this item have the en_US language code.

Other examples are http://hdl.handle.net/10919/19898 and http://hdl.handle.net/10919/19899. 

I would like to clean these up so they only have one value each for dc.date.accessioned and one dc.date.available. @keithgee or @kdweeks, do you have any records or recollection of this harvest, especially regarding dates?

**Comment by keithgee** [comment]
@alawvt, I see this problem you've found in the initial migration.

I'll look after lunch to see if I have anything from Layne/Nathan/Chris about any date issues. Layne gave Chris a lot of detailed and valuable feedback, but I think he was concerned mostly about the "date.issued" field instead of the other dates.

You mentioned the "en_US" language code, and I see that one pair of the date fields has that code, and the other doesn't. Once, you or Melissa explained to me under what circumstances the language code is added and when it isn't. I can't remember the specifics.

I know also that DSpace in some circumstances adds the dc.date.accessioned and dc.date.available fields automatically, so a "hunch" is that this was imported into a test system, and that we got lot of feedback from Layne. Then, after Chris fixed all of the issues, the collection was moved about three weeks later onto production, but the system decided to add the extra pair of date.accessioned and date.available fields during the import into production.

A flaw with this hunch is that we (VTechWorks, as well as the Computer Science department) would have presumably been looking at the import closely after it went into production. 

I'll do some digging.

**Comment by alawvt** [comment]
@keithgee, thank you for looking into this. As far as I know, DSpace always adds the dc.date.accessioned and dc.date.available fields when a new item is created. The en_US fields can get added manually with any method or automatically with the web submission form. That this came out of a test collection seems like a very reasonable hunch.

**Comment by alawvt** [comment]
I removed the 2013-05 values for dc.date.accessioned[en_US] and dc.date.available[en_US]. 996 items were changed with 20181030_10919_19372_dates.csv.


.
