### ISSUE TITLE
Update node, npm, compass and sass to enable local build

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#557]
To get `mvn clean package -Denv=dspace_local -Dmirage2.on=true` to work, 

I updated node and npm per [DS-4144 mirage2 fails to build corectly](https://jira.duraspace.org/browse/DS-4144), in 51315ee8f036a4c10652f5c1fec505e7de08cb20
```
<node.version>8.10.0</node.version>
<npm.version>6.5.0</npm.version>
```
I updated SASS and jruby per [DS-4115 Update SASS and Ruby ver](https://jira.duraspace.org/browse/DS-4115) in 76d9169b715ea250c8d24e27285ad0c201130ed1.

**Comment by keithgee** [comment]
@alawvt - similar patches have been applied to our vt_6_x_dev branch to repair the Mirage 2 build. I pulled in fixes for this issue that were committed to the main trunk of the upstream DSpace project, but have not yet been issued in an official release.

The node and npm versions from the official commits are different from your commit 51315ee:

```
<node.version>6.5.0</node.version>
<npm.version>3.10.8</npm.version>
```

Your versions are newer. That's presumably better, as long as it doesn't break anything, because of security fixes that are often included in the update. 

If you like, you can also apply commit 51315ee to the vt_6_x_dev branch; I'm thinking that it will be tested well before deploying DSpace 6 to VTechWorks anyway. Thanks!

**Comment by alawvt** [comment]
@keithgee, thank you very much for the information about the node and npm versions in DSpace 6. 05fd032199bfa01b7867339f6e20b94aec72abf2 changes these versions in vt_5_x_dev to match.
