### ISSUE TITLE
Tried to submit an ETD on vtechworks6-dev - "Permission denied"

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#578]
I tried to submit an ETD to the masters thesis collection on vtechworks6-dev and received the error, "Permission denied" at the end of the file upload step. I hit the back button and got the Upload File(s) step again, which said, "The item must contain at least one file." see screenshot, 
<img width="1224" alt="ETDSubmissionDSpace6" src="https://user-images.githubusercontent.com/13037168/57479578-ba0d1f00-726b-11e9-9da8-c2d6126ee77e.png">. When I tried uploading it again, I got "no such file or directory."

**Comment by alawvt** [comment]
I just tried to submit an article in the Library Test collection and also received the "No such file or directory" error after uploading a file.

**Comment by keithgee** [comment]
Well, this seems like a critical issue. I will have a look now.

**Comment by alawvt** [comment]
Thanks, @keithgee.

**Comment by keithgee** [comment]
In our initial setup we found that there were some permission problems with the assetstore because it had been synchronized from a system with different user and group ID numbers for the DSpace app user.
Apologies, I thought that this had been fixed when the system was opened for testing, but it seems this is still the same way.

I'm currently running a command to change ownership of all files to the DSpace app user (thus using the user id and group id on this system). This will take a while to finish, as it is visiting each file and directory individually.

I think it might be better if the userid/groupid of the DSpace app user matched on both systems, especially if the same technique will be used to synchronize the file system in the future.

**Comment by alawvt** [comment]
Thanks for working on this, @keithgee.

**Comment by keithgee** [comment]
@alawvt It really limits testing if you can't add items!

**Comment by alawvt** [comment]
Ah, but we get to record this configuration detail, which may be useful in the future.

**Comment by keithgee** [comment]
@alawvt, thanks for finding this. The task has finished now, and I'm able to upload a file and complete a submission.

**Comment by alawvt** [comment]
Great, @keithgee. I will also check it tomorrow.

**Comment by alawvt** [comment]
I am able to submit an item now. Thank you very much, @keithgee, for fixing this.
