### ISSUE TITLE
Check mail addresses for vtechworks6-dev

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#582]
Comparing the Control Panel configuration page, the mail server address differ between vtechworks and vtechworks6-dev. Please make sure that the 'SMPT Mail Server' and 'From Email Address' are correct.

**Comment by alawvt** [comment]
In https://github.com/VTUL/vtechworks/commit/89a467edd538a972fc022705bc87ce5df0705e2b#diff-a60e58808bf42c545ed0dc04a4d6d5f9,

`request.item.helpdesk.override = true`

However in the latest commit on vt_5_x_dev and on vtechworks prod it is 

`request.item.helpdesk.override = false` so let's just go with that. Thanks.

**Comment by keithgee** [comment]
Two items here:

1. From Email address and server were incorrectly configured on the DSpace 6 vtechworks dev server. They're normally handled in the Ansible playbooks, which weren't used for setup of this system. You can move them to local.cfg if it makes sense to do that. This should be on a checklist of things to test when dev/preprod/prod servers are deployed. (It probably already is on a list). 
2.  request.item.helpdesk.override = false is the default in dspace.cfg, and this currently appears on VTechWorks Dspace 6 Dev. (It's not in local.cfg because we're using the default setting and didn't override it).

**Comment by keithgee** [comment]
DSpace 6 dev is now using the correct settings.

*Closing - issue/s resolved.

**Comment by alawvt** [comment]
@keithgee, @kdweeks reports that she can now register a new user and received an email.
