### ISSUE TITLE
Unable to load SAF batches via command line

### ISSUE THREAD

**Issue by kdweeks** [VTUL/vtechworks#584]
When trying up upload a SAF batch following the steps here: https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/SAF_upload/, the import process breaks in two areas so far.  I can't proceed further. 

1) The directory at /dspace/assetstore/ingest/SimpleArchiveFormatBatchloads/ is read-only so I can copy the files from /tmp to the proper location to run the batch.  
Command and Error:

```
$ sudo -u vtechworks cp -r /tmp/20190503_10919_87720/ /dspace/assetstore/ingest/SimpleArchiveFormatBatchloads/

$cp: cannot create directory '/dspace/assetstore/ingest/SimpleArchiveFormatBatchloads/20190503_10919_87720': Read-only file system
```

2)  I tried to go ahead and run the batch from the /tmp directory just to see if the batch loader would work.  I got exceptions there as well.
Command and Exception:

```
$sudo -u vtechworks /dspace/bin/dspace import -a -e vtechworks-request-copy@vt.edu -c 10919/87720  -s  /tmp/20190503_10919_87720 -m /tmp/20190503_10919_87720/20190503_10919_87720.map -t

$**Test Run** - not actually importing items.
Destination collections:
Started: 1558041430726
Ended: 1558041431288
Elapsed time: 0 secs (562 msecs)
Exception: org.dspace.content.Item cannot be cast to org.dspace.content.Collection
java.lang.ClassCastException: org.dspace.content.Item cannot be cast to org.dspace.content.Collection
	at org.dspace.app.itemimport.ItemImport.main(ItemImport.java:449)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
```

**Comment by keithgee** [comment]
@kdweeks, I've marked this as a DSpace 6 issue. Let me know if that's not the case.
Thanks!

**Comment by keithgee** [comment]
Also, @kdweeks, please indicate if you were testing this on your local development environment, on the shared DSpace 6 dev server, or somewhere else.

**Comment by keithgee** [comment]
@kdweeks, I'm unable to access the specific instructions that you reference this morning because code.vt.edu Shibboleth login is inaccessible right now, possibly from a planned middleware maintenance window. I tried to recreate this from the instructions you provided.

I was able to load Anita's open textbook collection into your test batch load collection on the DSpace 6 test server. There was one difference - I had to preface a command that created files in the asset store with "sudo -u vtechworks" - so perhaps there's an error in the documentation.

The actual import command worked as you wrote without errors, though I also ran it again without the "-t" (test) parameter to actually import the items into the collection.

I think we may not have communicated to you how to login to the new DSpace 6 test system. It appears to me that you used the web interface to create the new collection, but when you got into the shell to run the commands, you were actually on another system, and not the new DSpace 6 test system. I couldn't see your username in the login history and the files you referenced in /tmp didn't exist. The error you see specifies that the handle you gave for import is the handle for an item, and not the handle for a collection, and this is the case on VTechWorks prod at least.

I will send a snippet to you from Anne and Soumik about how to access the shell on this test system. I'm going to close this issue because I can't duplicate it, but please reopen it if there are still problems importing items on the DSpace 6 test system.

**Comment by alawvt** [comment]
@keithgee, thank you for testing this. I also think the problem was the missing `sudo -u vtechworks` for the cp command.

**Comment by kdweeks** [comment]
@keithgee @alawvt  Hi, sorry I've been off for a couple of days and unable to respond.  I was using the using rain.lib.vt.edu.  I thought this was the DSpace testing server!  If not, that's another issue altogether.   I did use the proper command the first couple of times when I was trying to copy with the `sudo -u vtechworks` prepended to it.  I logged in this morning just to test again and I'm getting the same errors.

**Comment by keithgee** [comment]
@kdweeks, I reopened this issue. Please verify that you're using the correct port number when you connect. This is in the email that I sent to you with the chat. Also, please let me know what the "hostname" command returns once you're logged in.

**Comment by kdweeks** [comment]
@keithgee I was using the wrong port!!  I was using 2023 on rain.lib.vt.edu.  Since I put that in my ssh config file when I first logged in, I didn't think about it again.  I was logging into: `vtechworks@vtechworks-pprd` before.  Using port 2030, I can't login at all 🙁.   

I get the following: 
`kdweeks@rain.lib.vt.edu: Permission denied (publickey).`

**Comment by alawvt** [comment]
You may to ask @soumikgh to add you and then add the public key to your known keys.

**Comment by kdweeks** [comment]
@alawvt @keithgee -  @soumikgh added my public key.  At least I'm on the correct server now - duh!  FYI vtechworks-pprd is having trouble with command line batch loading.

**Comment by kdweeks** [comment]
@keithgee The command line batch loading process we use is working beautifully on DSpace 6 dev!
