### ISSUE TITLE
SWORD v1 error in vtechworks6-dev.cloud.lib.vt.edu

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#607]
SWORDv2 seems to work ok on https://vtechworks6-dev.cloud.lib.vt.edu. 

However https://vtechworks6-dev.cloud.lib.vt.edu/sword/servicedocument yields the error:
```
HTTP Status 500 – Internal Server Error

Type Exception Report

Message The schema validator returned: Unable to create requested service [org.hibernate.engine.spi.CacheImplementor]

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.dspace.core.exception.DatabaseSchemaValidationException: The schema validator returned: Unable to create requested service [org.hibernate.engine.spi.CacheImplementor]
	org.dspace.core.Context.init(Context.java:170)
	org.dspace.core.Context.<init>(Context.java:126)
	org.dspace.sword.SWORDAuthenticator.constructContext(SWORDAuthenticator.java:94)
	org.dspace.sword.SWORDAuthenticator.authenticate(SWORDAuthenticator.java:115)
	org.dspace.sword.DSpaceSWORDServer.doServiceDocument(DSpaceSWORDServer.java:58)
	org.purl.sword.server.ServiceDocumentServlet.doGet(ServiceDocumentServlet.java:137)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

Note The full stack trace of the root cause is available in the server logs.
Apache Tomcat/8.5.39 (Ubuntu)
```

**Comment by alawvt** [comment]
In attempting to troubleshoot this error, I tried
`sudo -u vtechworks ./dspace database test`
and got:
```
OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   30715
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /dspace/log/checker.log.2019-07-19 (No space left on device)
```
The database did connect but it continued to complain about space for logging.

**Comment by alawvt** [comment]
Also noting nginx is not used in https://vtechworks6-dev.cloud.lib.vt.edu:
```
$ cd /etc/nginx
-bash: cd: /etc/nginx: No such file or directory
```

**Comment by keithgee** [comment]
Thanks, Anne. This is interesting. It previously worked, and based on what you found in the log files, this may be an issue with disk space.

I don't think I should spend any time getting this working on this particular system again. This system was deployed with the old Ansible project, and not the new one that we're now working with, and as you mentioned, it used Apache httpd instead of nginx.

Given that we're going to use vtechworks.dev as our test system now, and this vtechworks-6-dev.cloud.lib.vt.edu hasn't been maintained for several months as is different from our current project, I'm going to close this issue.

Closing.
