### ISSUE TITLE
Update SOLR stats after migration to DSpace 6

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#621]
Update SOLR stats after migration to DSpace 6 using Terry Brady's statistics upgrader, see https://github.com/VTUL/vtechworks/issues/618 and 
https://code.vt.edu/it-services/vtlibans_dspace/issues/129

**Comment by alawvt** [comment]
sample run:
```
vtkeithg@vtechworks-prod:~$ sudo -u vtechworks /dspace/bin/dspace dsrun org.dspace.util.SolrUpgradePre6xStatistics --num-rec 2001 --batch-size 500
 * This process should be run iteratively over every statistics shard 
 * until there are no remaining records with legacy ids present.
 * This process can be run while the system is in use.
 * It is likely to take 1 hour/1,000,000 legacy records to be udpated.
 *
 * This process will rewrite most solr statistics records and may temporarily double 
 *  the size of your statistics repositories.  Consider optimizing your solr repos when complete.
 * -------------------------------------------------------------------
No index name provided, defaulting to : statistics
Connecting to http://localhost:8080/solr/statistics
=================================================================
    *** Statistics Records with Legacy Id ***
      66,950,772    Bistream View
      33,025,656    Item View
       1,045,616    Collection View
         867,656    Community View
       9,971,675    Community Search
       7,474,511    Collection Search
          12,596    Unexpected Type & Full Site
    --------------------------------------
     119,348,482    TOTAL
=================================================================
             500  Processed... (    19 sec; 0:00:19; DB cache:      5/       5; Docs:    500)
           1,000  Processed... (    86 sec; 0:01:45; DB cache:      9/       9; Docs:    500)
           1,500  Processed... (    81 sec; 0:03:07; DB cache:     11/      11; Docs:    500)
           2,000  Processed... (    78 sec; 0:04:25; DB cache:     17/      17; Docs:    500)
           2,001      TOTAL... (   355 sec; 0:05:55; DB cache:     17/      17; Docs:      1)
=================================================================
    *** Statistics Records with Legacy Id ***
      66,950,772    Bistream View
      33,025,656    Item View
       1,045,616    Collection View
         865,656    Community View
       9,971,675    Community Search
       7,474,511    Collection Search
          12,596    Unexpected Type & Full Site
    --------------------------------------
     119,346,482    TOTAL
=================================================================
```
It’s probably better to not use the --batch-size parameter and just use the default of 10000 and --num-rec can be set high; there are now 120 million records.

Start it in a screen session if it's long running.
```
sudo -u vtechworks screen -ls
There is a screen on:
    9592.pts-0.vtechworks-prod    (09/13/2019 12:02:32 PM)    (Detached)
1 Socket in /run/screen/S-vtechworks
```

**Comment by alawvt** [comment]
Progress report: 113, 216, 328 items remaining of the 119, 346,482 records that remained on Friday. We got through about 6 million records in three days.

**Comment by keithgee** [comment]
I've temporarily stopped this process in case it has been causing recent reported problems with slow updates.

**Comment by alawvt** [comment]
@keithgee changed the SOLR stats conversion schedule to only run at night. This resolved #641.

**Comment by keithgee** [comment]
Update: I've been running this process again, but only at night. We currently have 106, 141, 328 records remaining to update.

I've also disabled the nightly tasks that optimize the solr cores for statistics, search, and oai each night so that the statistics updater doesn't compete with them for resources. I think that we should leave these tasks disabled permanently even after the statistics records are updated, or if we're going to run them, perhaps run them once a month at most. I'm unsure why they were set to run each night (this may have been a mistake) and I have a hunch that this may have contributed to some of the downtime in recent months.

**Comment by alawvt** [comment]
Is there a way to run the SOLR statistics conversion process on a local Vagrant install? I'm given to understand it will run faster on an SSD?
The production instance has been responding  slowly since the statistics conversion was initiated, and we have been getting flooded with unresponsive/downtime messages which makes it easier for legitimate warnings to go unnoticed.
Other than increasing the monitoring warning traffic, it has also affected other applications running on the same host/storage server; and we had to move an application off to a different host. We could just turn off monitoring for VTechworks for the time being, but a local conversion will be preferable, I think.  - @soumikgh

**Comment by alawvt** [comment]
Can run conversion on a local install, mostly. I need a plan for merging the updated records with the new records that will be created on production during the time that the update process is ongoing on the local system.
I don’t know if it would help any other problems we are seeing, but it’s also possible for DSpace to connect to Solr running on a different host - unfortunately DSpace is coupled to an out of date version of Solr, though. - @keithgee

**Comment by keithgee** [comment]
We'll go ahead and look at updating the statistics offline on a system with an SSD.

**Comment by keithgee** [comment]
Offline on a device with an SSD, I have used the DSpace solr statistics sharding tool, as well as Terry's index updater tool, to create Solr indices with the IDs updated to the new UUIDs for the years 2012 through 2017. 2011 and 2018 need more work. Once I was able to properly configure a VM for this purpose, running the update tool on a VM on my local desktop processed about 3 million records per hour, as compared to approximately 100,000 records per hour when this was attempted on the production server.

The plan has been to leave these statistics separate by year, and have each year run in a separate solr shard, all on the same machine. According to the DSpace documentation, having old years separate from the main core improves performance. However, during an ATS meeting recently, it was brought to my attention that running multiple shards on the same system might add overhead with little benefit, thus slowing things down more. I imagine this might be especially true since the Solr index isn't installed on an SSD on our server.

Because I don't know what will happen with performance, instead of installing all of the years, I'd like to install the years piecemeal to see what happens. I have some more testing to do locally first to make sure I can safely purge statistics from the original index. 

I think ideally, we would have the Solr indices for VTechWorks running on an SSD to improve performance. It would have saved a lot of work and experimentation here, too, and would be less risky.

**Comment by alawvt** [comment]
@keithgee, thank you VERY much for toiling away on this. That's great that the local SSD is so much faster. It will be interesting to see how the shards affect the performance.

**Comment by keithgee** [comment]
Currently running tests and preparing to install shards on dev as per our latest plan, https://code.vt.edu/it-services/vtlibans_dspace/issues/140.

**Comment by keithgee** [comment]
A bit (!) of a delay, but this is complete. Shards 2011 - 2021 are installed on production, and shards from 2011-2019 have been converted to have the UUID. (2020 and 2021 shards did not have any records missing the UUID, given that our installation was in 2019).

I will put more details about sharding in our private wiki on Gitlab.

**Comment by alawvt** [comment]
@keithgee, thank you so much for completing this Herculean task! @soumikgh, thank you very much for setting up the virtual machined to enable this work. No longer are there the legacy stats subtotals in the stats pages:
<img width="1188" alt="SOLRstats_after_sharding_and_conversion" src="https://user-images.githubusercontent.com/13037168/182159684-64446a86-0786-44a5-8ea8-95d47de1eb49.png">
