### ISSUE TITLE
Check REST login in DSpace 6

### ISSUE THREAD

**Issue by alawvt** [VTUL/vtechworks#638]
EFARS is getting a 401 error trying to harvest from vtechworks. According to https://wiki.duraspace.org/display/DSDOC6x/REST+API, it should be a command like 

`curl -v -X POST --data "email=alaw@vt.edu&password=secret" https://vtechworks.lib.vt.edu/rest/login` 

but I am getting the 401, too. The immediate concern is that this is causing the Elements harvest to fail.

In DSpace 5, I had used 

`curl -H "Content-Type: application/json" --data '{"email":"alaw@vt.edu", "password":"secret"}' https://vtechworks.lib.vt.edu/rest/login -v` 

but that also fails.

[VTechWorks REST-API Wiki page](https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/rest_api)

**Comment by keithgee** [comment]
Hi, @alawvt. The first curl command that you posted works for me (using real usernames and passwords, of course). 

Some characters in your password might be complicating something. You might try using --data-urlencode instead of --data, and passing each parameter separately, like so:

`curl -v -X POST --data-urlencode "email=alaw@vt.edu" --data-urlencode "password=secret" https://vtechworks.lib.vt.edu/rest/login`

I'm not sure why EFARS is getting a 401 error, but I'd check to see that they're set up for DSpace 6 (not 5) and that they are using the correct username and password.

**Comment by alawvt** [comment]
@keithgee, thank you very much for testing this. I just submitted a ticket to Symplectic and linked this issue.

**Comment by keithgee** [comment]
Thanks. Also, I was just re-reading this and wasn't sure if the 401 Error (that EFARS is getting) is during the login phase, or at some other point, but it sounds mostly like they can't login.

**Comment by alawvt** [comment]
I believe it is login, but I can't tell for sure.

**Comment by keithgee** [comment]
The issue with EFARS harvesting of DSpace has been resolved by Symplectic.

Edit: Adding additional detail. The synchronizer on the Elements side had to be restarted. Even though the settings had been changed from DSpace 5 to DSpace 6, this process needed to be restarted before the process used the new settings.
*** Closing
