### ISSUE TITLE
Retrieve AdvanceVT posters stuck in task pool

### ISSUE THREAD

**Issue by cecross1** [VTUL/vtechworks#644]
I submitted some AdvanceVT posters through the submission form last week, and they seem to be stuck in an under review status. Peggy Layne used to be the approver for all AdvanceVT collections, but she's retired. @pyc1 can't approve them either, because they're not showing up in his task pool. Can someone help me figure out how to get these approved? A screenshot is attached for your reference. Thanks!
<img width="1384" alt="AdvanceVT submissions creenshot" src="https://user-images.githubusercontent.com/26065475/65603435-a8ef5100-df73-11e9-8473-f87c73b2d374.png">

**Comment by alawvt** [comment]
I do not know of any way to access these submissions. @keithgee, do you have any ideas?
@cecross1, there is no Accept/Reject group for the AdvancedVT, Posters collection, https://vtechworks.lib.vt.edu/handle/10919/71888, so I wonder why it would have gone into the approval queue. Perhaps @pyc1 deleted the Accept/Reject group after you submitted the items. It might be best to wait until he is back on Monday to figure out what happened. In general, the Approval or Notify groups should be added to all Accept/Reject groups so we can access items. We could also check with Peggy to see if she added them to her task pool. If so, she could approve them.

**Comment by keithgee** [comment]
I'll look at this while I'm waiting and again when I'm back at my desk.

**Comment by keithgee** [comment]
@cecross1 I have approved these items to get them out of the workflow cue. They're in the collection now. I'll update this issue with more details about how this was done when I'm back.

**Comment by cecross1** [comment]
@keithgee This is great! Thanks so much!

**Comment by keithgee** [comment]
Here are the rough steps that got these items out of the workflow, and that may be helpful for similar events where all of the users that were part of the workflow group when items were submitted are not available:

1. As an administrator, use the DSpace people/groups tools to add the absent user with pending tasks (in this case, Peggy Layne) to a group (in this case, admin_collections) that has administrative access to the owning collection, if the user does not already belong. The tools that search for users behave in odd ways sometimes; you may have to search for variations or part of the name.
2.  A user with shell access edits the /dspace/config/local.cfg file, adding the following line: `webui.user.assumelogin = true`. This change will allow a DSpace administrator to login as another user in the next step. Tomcat does not need to be restarted, because version 6 of DSpace will automatically detect the configuration change.
3. As an administrator, login in via the web interface, use the "People" tool to search for the absent person's account (Peggy), click on the person's name, and then click the "Log in as E-Person" button found on the "Edit an E-Person" page. You are now temporarily acting as the absent person (Peggy).
4. You, the administrator, acting as the absent person, click on the "Submissions" item on the "My Account" section of the menu on the right side of the page, and from this area claim the workflow tasks and approve the items.
5. You, the administrator,  log out from the web interface to stop acting as the absent user.
6. You, the administrator, remove the user (Peggy) from whichever groups (admin_collections) they were added to as part of this process.
7. You, the administrator, log out completely 
8.  Edit the local.cfg file to remove the line that was added previously. Again, this requires shell access, but does not require a restart of Tomcat. This disables the "Log in as E-Person" button again.

Side note:  If Peggy has retired and won't be the approver for items in this collection any more, and there's no replacement approver for her department, and we still have items to submit to this collection, it might be best to just remove the workflow steps and also the collection administrators from this collection so that when Carrie submits the items will go immediately into the collection.

** Closing

**Comment by alawvt** [comment]
@keithgee, thank you very much for handling this issue and documenting the procedure, which I have added to the VTechWorks wiki page, [Task pool retrieval](https://code.vt.edu/digital-research-services/VTechWorks_Documentation/wikis/task_pool_retrieval).

**Comment by kdweeks** [comment]
+1 - Nice Documentation!

Kimberli Weeks
kdweeks@vt.edu
w. (540) 231-2674 c. 540-835-9136
Technical Director,
Scholarly Communications
University Libraries, Virginia Tech
http://scholar.lib.vt.edu
