### ISSUE TITLE
Movie Poster not showing in Chrome

### ISSUE THREAD

**Issue by kdweeks** [VTUL/vtechworks#660]
When viewing video records in VTechWorks from Chrome (Version 78.0.3904.108) I am unable to see the movie poster.  All I am able to see in Chrome is a blank, black square where the movie poster should be.  I tested this in Firefox (68.3.0esr ) and the movie poster showed up fine.

Here is an example of a video record:   
https://vtechworks.lib.vt.edu/handle/10919/95925

**Comment by alawvt** [comment]
The movie poster appears normally in both Firefox and Chrome on my iMac here.

Hmm, now that it has played for a second, when I reload the item, the movie poster is black in Chrome.

Hmm, I tried loading several other videos and as they load, they are flashing the movie poster for split second, then just appearing black. These appear normally in Firefox.

Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by keithgee** [comment]
The fix for this is to change `preload="auto"` to `preload="none"` in the HTML5 video tag in the [item-view.xsl ](https://github.com/VTUL/vtechworks/blob/vt_6_x_dev/dspace/modules/xmlui-mirage2/src/main/webapp/themes/vtmirage2/xsl/aspect/artifactbrowser/item-view.xsl) file.

I suspect that when video preload is turned on, Chrome expects that the video will autoplay.

As a reminder, I've been asked to hold off on doing video related work until the upcoming discussion about how ATS can make video processing easier for VTechWorks - but this is a quick theme change if others are allowed and ambitious!

**Comment by alawvt** [comment]
@keithgee, thank you for updating these video issues.

**Comment by jimtuttle** [comment]
Hi, this is waiting on me to get clarification on related issues.
