### ISSUE TITLE
QT files play as only audio?

### ISSUE THREAD

**Issue by amandafrench** [VTUL/vtechworks#69]
Report that item https://vtechworks.lib.vt.edu//handle/10919/36551 used to play as video and now only plays as audio. Related to #31?

**Comment by keithgee** [comment]
Hi, Amanda. My guess is that this is related to a change in your operating system or browser. It won't play in my Safari browser - latest version. I can download it with Firefox, and then open it with QuickTime, which now converts it to a .mov file before it will play it.

Can you narrow this down for a range of time when it broke? Does it work differently with different browsers/computers?

It's unlikely that this is related to #31, the video playback feature, because that feature only activates when both an mp4 and webm file are present in the item. Video playback was never intended to support playback of QT files. If it worked previously, it was only coincidental, and not anything to do with that feature.

I can convert it to the supported formats for video playback if that would be helpful.

**Comment by alawvt** [comment]
I played one in Firefox and was only able to hear the audio.

**Comment by keithgee** [comment]
This is for Gail's presentation on November 3. I'll convert the files to the supported formats. I probably won't be able to devote time to figuring out why only the audio is playing in QT files. This format is unsupported, except that we'll allow people to download the exact file that was deposited.

**Comment by amandafrench** [comment]
Thanks much, @keithgee. Not really your job, but Gail will be grateful. Close the issue when the files in that item are converted.

**Comment by keithgee** [comment]
I've added .webm and .mp4 files for this item, along with thumbnails and a movie "poster".

http://vtechworks.lib.vt.edu/handle/10919/36551

Results are not great.
- the embedded video playback system currently only supports 1 video per item. this item has two. However, the videos can still be played by clicking on the appropriate .mp4 or .webm (for Chrome) links
- the embedded video playback system is stretching this 320x200 video into an 854 pixel window, trying to fill a much larger space with the pixels. It's blocky. The videos can be forced to play in a smaller window if the mp4 or .webm links are clicked, which makes things appear smoother.

I spoke with Gail, and she said the videos are from 1997 and she was aware they are low quality and is fine with this work.

Closing.
