### ISSUE TITLE
Add a captcha/recaptcha form

### ISSUE THREAD

**Issue by kayiwa** [VTUL/vtechworks#73]
Heya,

Is it possible to enable a "prove you are not a spambot" feature in DSpace? Jane Wills is getting periodic annoying spam floods which admittedly could be mailheader spoofing. 

Cheers.

**Comment by amandafrench** [comment]
I just wrote @alawvt about this today! Thread here: https://groups.google.com/forum/#!topic/dspace-tech/mTlDmDWRghw (but no code). However, we have decided (especially since JW is leaving) to restrict requests to registered users for the time being, as described in #72. That should solve the spam issue, unless of course people start creating spam accounts. Closing.

**Comment by alawvt** [comment]
dspace-community@googlegroups.com 11/12/15 posting, http://groups.google.com/group/dspace-community/msg/1e5dd03782608?utm_source=digest&utm_medium=email, had detail instructions for adding a Captcha.
