### ISSUE TITLE
DSpace chokes on large uploads (over 2 GB)

### ISSUE THREAD

**Issue by mello99** [VTUL/vtechworks#91]
Hi all, I've been trying to upload 2 event capture videos (from Jing's computer) and DSpace has choked on both of them. After the item upload reaches 100%, I get a notice that says "Notice: Error while uploading file." I'll try again, but this has happened several times, so it appears to be a pattern. Thanks.

**Comment by keithgee** [comment]
Thanks @mello99. Ginormous files will need to be squeezed into VTechWorks using the command line utilities.

**Comment by BorwickAtVT** [comment]
FWIW: https://jira.duraspace.org/browse/DS-2359

**Comment by keithgee** [comment]
@mello99, how big are the files? The fix that John sent may get us up to 4 gigabytes.

**Comment by mello99** [comment]
2.24 and 2.26 GB

**Comment by mello99** [comment]
2.24 and 2.26 GB

**Comment by alawvt** [comment]
I attempted to upload these two videos with the itemupdate command line utility. It gave permission errors along the way for /dspace/log/checker.log.2015-11-10 (Permission denied) and
/dspace/log/solr.log.2015-11-10 (Permission denied). I have reported those errors in a TeamDynamix request. 

Despite the permission errors, the command seemed to run. The files are now in the two items but they won't play. The descriptions says they are slightly smaller is size than the originals but according to the dc.description.provenance fields, they are the same size as the originals: 

The Victoria Stodden video, http://vtechworks.lib.vt.edu/handle/10919/63898,
```
Added 1 bitstream(s) on 2015-11-10T20:59:19Z : No. of bitstreams: 1
2015_OA_Week_Keynote.mp4: 2262620495 bytes, checksum: 068eb8a8f18b38cefd9382134d1c7dca (MD5)
```
The Naomi Oreskes video, http://vtechworks.lib.vt.edu/handle/10919/6390,
```
Added 1 bitstream(s) on 2015-11-10T20:59:53Z : No. of bitstreams: 1 Oreskes_Naomi20150902.mp4: 2243422806 bytes, checksum: 088b2c11ef30d45fb76f9b76060a3664 (MD5)
```
@keithgee, do you have any ideas?

**Comment by keithgee** [comment]
@alawvt, what do you mean that they won't play?

The videos have to be in a particular format for the embedded playback controls to show up. My understanding is that the Victoria Stodden video in particular was just going in as a placeholder so that Philip could share it, until the video could be encoded in the proper formats.

We should meet with Event Capture group soon to figure out the workflow.

**Comment by keithgee** [comment]
@alawvt I see the (Firefox won't run. Safari indefinitely "Loading" comment). Most likely is the video format - Event Capture is trying a new encoding process with new software procured last month.

**Comment by alawvt** [comment]
@keithgee, thanks for taking a look at this. There were 4 recent videos from Event Capture. @mello99 was able to load the two smaller ones and they are viewable from Firefox. We could find out if there was anything about these two. The originals play fine in QuickTime.

Also, @kayiwa fixed the permission errors mentioned earlier.

**Comment by keithgee** [comment]
I have tracked down the problem downloading large files. The web browsers request partial ranges of the files with HTTP headers like this:
Range: bytes=2238906368-
The DSpace XMLUI is based on Cocoon. Cocoon's Byte Range handler has code that tries to parse each number in the byte range as an integer.
In Java, the maximum size of a signed integer is 2,147,483,647, which is less than 2238906368. This throws a NumberFormatException back to DSpace, which returns a 416 HTTP Status code to the browser:
HTTP/1.1 416 Requested Range Not Satisfiable

The browser doesn't get the file.

I'm don't know yet what the best workaround is - I'm not sure that Cocoon is an active project, and the DSpace community is looking to move away from Cocoon (I've heard) with its next interface system.

For now, I've put lower quality (but acceptable, and smaller) versions of the two mp4s in the two items. Since I'm in there, I'll also add thumbnails, movie posters, and webm versions. The smaller mp4s are now playing and downloadable.

This issue seems to have split into two issues - uploading large files over 2G, and downloading large files over 2G. We have a temporary resolution for both of these issues (though we're sure to revisit this again soon) so I will close the issue.
Closing!

**Comment by alawvt** [comment]
That's great that you have figured this out, @keithgee. We should tell event capture about the size limit and keep it in mind for other large files. Is this a problem for all types of files over 2GB, say a data file or extremely large BTD? If so, we might need to review our bitstreams for possible offenders and possibly take other actions.

**Comment by keithgee** [comment]
Yes, all bitstreams.
We have two larger:
MeganWawro_1.mov
Scenery_1.mp4

**Comment by alawvt** [comment]
https://groups.google.com/g/dspace-tech/c/CBG8lAJ0BeQ/m/wFt67lijBAAJ

>There is no limit anymore. Since dspace 6.1 it is fixed (https://github.com/DSpace/DSpace/pull/1723).

>I can confirm that in our DSpace 6.3 installation big movie files up to 6.5 GB was possible. We will prevent this in the future. Similiar to JSPUI.

>Regards,
>Manuele
